// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogKind } from "./LogKind";
import type { LogLevel } from "./LogLevel";

export type LogEntry = { ts: string, level: LogLevel, kind: LogKind, source: string, system: string, event: string, service?: string, env?: string, traceId?: string, spanId?: string, requestId?: string, error?: string, stack?: string, method?: string, path?: string, status?: number, durationMs?: number, cfRay?: string, cfColo?: string, ip?: string, userAgent?: string, };
