// Generated by gen-adapters.ts (ADR-0004 Phase 0) — do not edit.
// Source: cad-schema.json boundaries [588b1e6aaa9e]
// Target: sync-test / SyncWasmAdapter implementation

// Test SyncWasmAdapter — wraps the generated async WASM functions.
// Identical shape to browser adapter but uses the test context WASM loader.
// Generated from cad-schema.json boundaries.modules['truck-sync'] (clientAdapter:true, no merge_docs).

import { syncCreate, syncApplyOp, syncMergeDocs, syncGetOps, syncGetOpCount, syncSetOpEnabled, syncSetGroupEnabled, syncRollbackTo, syncGetName, syncSetName, syncGetReplayOps } from './sync-wasm.generated';
import type { SyncWasmAdapter } from '../../ts/sync-wasm-adapter.generated';

/** SyncWasmAdapter implementation using the real sync WASM — no mocks. */
export const testSyncWasmAdapter: SyncWasmAdapter = {
    create_doc: () => syncCreate(),
    apply_op: (doc: Uint8Array, opJson: string) => syncApplyOp(doc, opJson),
    merge_docs: (local: Uint8Array, remote: Uint8Array) => syncMergeDocs(local, remote),
    get_ops: (doc: Uint8Array) => syncGetOps(doc),
    get_op_count: (doc: Uint8Array) => syncGetOpCount(doc),
    set_op_enabled: (doc: Uint8Array, opId: string, enabled: boolean) => syncSetOpEnabled(doc, opId, enabled),
    set_group_enabled: (doc: Uint8Array, groupId: string, enabled: boolean) => syncSetGroupEnabled(doc, groupId, enabled),
    rollback_to: (doc: Uint8Array, actorId: string, toIndex: number) => syncRollbackTo(doc, actorId, toIndex),
    get_replay_ops: (doc) => syncGetReplayOps(doc),
    get_name: (doc: Uint8Array) => syncGetName(doc),
    set_name: (doc: Uint8Array, name: string) => syncSetName(doc, name),
};
