version: '3'

# ============================================================================
# plat-trunk - CAD Kernel Platform
#
# Works with:
#   - task + process-compose (standalone)
#   - xplat (bundles both)
#
# Usage:
#   task deps:install   # Install dependencies
#   task up             # Start services
#   task truck:ci       # Build and test
# ============================================================================

env:
  GOWORK: 'off'

# Load .env first, then .env.local overrides (for secrets)
dotenv: ['.env', '.env.local']

includes:
  # Local systems
  envsubst:
    taskfile: ./systems/envsubst/Taskfile.envsubst.yml
    vars:
      ROOT_DIR: '{{.PWD}}'
  truck:
    taskfile: ./systems/truck/Taskfile.truck.yml
    vars:
      ROOT_DIR: '{{.PWD}}'
  gh:
    taskfile: ./systems/gh/Taskfile.gh.yml
    vars:
      ROOT_DIR: '{{.PWD}}'

vars:
  BIN_DIR: .bin
  DATA_DIR: .data
  SRC_DIR: .src

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ===========================================================================
  # Process Compose
  # ===========================================================================
  up:
    desc: Start all services with TUI
    cmds:
      - process-compose up -f process-compose.yml --port ${PC_PORT:-8000}

  "up:detached":
    desc: Start all services in background
    cmds:
      - process-compose up -f process-compose.yml -D -t=false --port ${PC_PORT:-8000}

  down:
    desc: Stop all services
    cmds:
      - process-compose down

  attach:
    desc: Attach to running TUI
    cmds:
      - process-compose attach

  # ===========================================================================
  # Debug
  # ===========================================================================
  debug:
    desc: Print root vars and env
    cmds:
      - echo "=== Root Vars ==="
      - echo "BIN_DIR={{.BIN_DIR}}"
      - echo "DATA_DIR={{.DATA_DIR}}"
      - echo "SRC_DIR={{.SRC_DIR}}"
      - echo "PC_PORT=${PC_PORT:-8000}"
    silent: true

  debug:all:
    desc: Print debug info for all systems
    cmds:
      - task: debug
      - task: envsubst:debug:self
      - task: truck:debug:self
      - task: gh:debug:self

  # ===========================================================================
  # Deps
  # ===========================================================================
  deps:install:
    desc: Install all external dependencies
    deps:
      - envsubst:deps:install
      - truck:deps:clone
      - gh:deps:install

  deps:clean:
    desc: Remove all installed dependencies
    cmds:
      - rm -rf {{.BIN_DIR}}
      - rm -rf {{.SRC_DIR}}
      - rm -rf {{.DATA_DIR}}
