/**
 * sync-client.ts — ADR-0008 Phase 1: SyncClient
 *
 * Single class that owns the full sync protocol:
 *   - CRDT doc bytes (Automerge)
 *   - Storage (IDB in browser, R2 in CF worker, Memory in tests)
 *   - Server sync round-trip (HTTP in production, direct fn in tests)
 *   - Cross-tab/cross-actor messaging (BroadcastChannel in browser, direct in tests)
 *   - Network state (online/offline, unsent op queue, auto-resync on reconnect)
 *   - Structured tracing (every event logged, assertable in tests and CI)
 *
 * The WASM adapter is the REAL sync WASM in all environments.
 * Only storage and network are swapped between production and tests.
 *
 * Lives in systems/sync/ts/ — imported by any consuming system.
 * Has zero knowledge of geometry, replay, or system-specific state.
 */

import type { Operation } from '../shared/types';
import type { SyncWasmAdapter } from '../shared/wasm-adapter';
export type { SyncWasmAdapter }; // re-export for consumers (history-domain, tests)

// ── Browser type stubs (not available in CF Workers tsconfig) ────────────────
// These satisfy tsc when compiled without DOM lib (e.g. CF Workers).
// At runtime in browsers, the real globals are used via globalThis.
/* eslint-disable @typescript-eslint/no-explicit-any */
interface BroadcastChannelLike { onmessage: ((ev: MessageEvent) => void) | null; postMessage(data: any): void; close(): void; }
/* eslint-enable @typescript-eslint/no-explicit-any */

// ── Adapter interfaces ────────────────────────────────────────────────────────

// SyncWasmAdapter imported from sync-wasm-adapter.generated.ts (generated by gen-adapters.ts)

/** Persistent storage — IDB in browser, R2 in worker, Map in tests. */
export interface SyncStorageAdapter {
  save(modelId: string, bytes: Uint8Array): Promise<void>;
  load(modelId: string): Promise<Uint8Array | null>;
  delete(modelId: string): Promise<void>;
}

/**
 * DocStore — alias for SyncStorageAdapter used by R2DocStore in the CF worker.
 * Keeping this name for backward compat with worker/src/doc-store.ts imports.
 */
export type DocStore = SyncStorageAdapter;

/**
 * Network adapter — HTTP+SSE in production, direct function call in tests.
 *
 * NOTE: The adapter owns the connection lifecycle. `postSync` sends local doc
 * bytes to the server and receives the merged doc back. `onRemoteChange`
 * registers a callback that fires whenever another actor changes the doc
 * (SSE `doc-changed` event in production, direct invocation in tests).
 */
export interface SyncNetworkAdapter {
  postSync(modelId: string, bytes: Uint8Array, actorId: string): Promise<Uint8Array | null>;
  onRemoteChange(modelId: string, callback: () => void): void;
  disconnect(): void;
}

// ── Structured tracing ────────────────────────────────────────────────────────

export type SyncEventType =
  | 'add_op'
  | 'undo_op'
  | 'redo_op'
  | 'undo_group'
  | 'redo_group'
  | 'rollback'
  | 'load_storage'
  | 'save_storage'
  | 'sync_start'
  | 'sync_complete'
  | 'sync_error'
  | 'remote_change'
  | 'merge'
  | 'network_online'
  | 'network_offline'
  | 'queue_op'
  | 'flush_queue'
  | 'load_sync'
  | 'sync_retry'
  | 'broadcast_send'
  | 'broadcast_receive'
  | 'presence_update'
  | 'compact';

export interface SyncLogEntry {
  ts: number;
  modelId: string;
  actorId: string;
  event: SyncEventType;
  detail: Record<string, unknown>;
}

/**
 * SyncMessage — BroadcastChannel wire format for cross-tab CRDT merge.
 *
 * Tab A applies an op → sends SyncMessage via BroadcastChannel.
 * Tab B receives → merges doc bytes → triggers replay.
 *
 * Owned here (sync system) not in truck — cross-tab sync is a sync concern.
 */
export interface SyncMessage {
  type: 'doc_update';
  modelId: string;   // Filter: only merge if matches local model
  bytes: number[];   // Uint8Array serialised as Array (structured clone safe)
  tabId: string;     // Filter: ignore own tab's messages
}

// ── SyncClient ────────────────────────────────────────────────────────────────

/** Presence state — cursor, selection, or custom fields. Consumer defines the shape. */
export interface PresenceState {
  actorId: string;
  name?: string;
  [key: string]: unknown;
}

export interface SyncClientOptions {
  actorId: string;
  debounceMs?: number;       // default 2000
  maxLogEntries?: number;    // default 200
  maxRetries?: number;       // default 3 (0 = no retry)
  retryBaseMs?: number;      // default 1000 (exponential: 1s, 2s, 4s)
  maxDocBytes?: number;      // default 0 (0 = no limit, triggers compaction when exceeded)
  tabId?: string;            // default: crypto.randomUUID()
}

export class SyncClient {
  private _docBytes: Uint8Array | null = null;
  private _modelId: string | null = null;
  private _syncing = false;
  private _syncTimers = new Map<string, ReturnType<typeof setTimeout>>(); // per-model debounce (G17)
  private _activeSyncPromise: Promise<void> | null = null;
  private _online = true;
  private _pendingSync = false;  // queued while offline
  private _broadcast: BroadcastChannelLike | null = null; // G11
  private _presence = new Map<string, PresenceState>(); // G14

  readonly tabId: string;
  readonly syncLog: SyncLogEntry[] = [];
  private readonly _maxLog: number;
  private readonly _debounceMs: number;
  private readonly _maxRetries: number;
  private readonly _retryBaseMs: number;
  private readonly _maxDocBytes: number;

  // ── Events emitted to consumers ──────────────────────────────────────────
  onRemoteOps?: (ops: Operation[]) => void;
  onSyncComplete?: (hadNewOps: boolean) => void;
  onNetworkState?: (online: boolean) => void;
  onPresence?: (actors: PresenceState[]) => void;
  onError?: (error: Error, context: string) => void;

  constructor(
    private readonly wasm: SyncWasmAdapter,
    private readonly storage: SyncStorageAdapter,
    private readonly network: SyncNetworkAdapter,
    private readonly opts: SyncClientOptions,
  ) {
    this._debounceMs = opts.debounceMs ?? 2000;
    this._maxLog = opts.maxLogEntries ?? 200;
    this._maxRetries = opts.maxRetries ?? 3;
    this._retryBaseMs = opts.retryBaseMs ?? 1000;
    this._maxDocBytes = opts.maxDocBytes ?? 0;
    this.tabId = opts.tabId ?? (typeof crypto !== 'undefined' ? crypto.randomUUID() : Math.random().toString(36));
  }

  // ── Lifecycle ─────────────────────────────────────────────────────────────

  /**
   * Start listening for remote changes on a model.
   * Call after loadFromStorage or createDoc.
   */
  listen(modelId: string): void {
    this.network.onRemoteChange(modelId, () => {
      this._log('remote_change', { modelId });
      this._triggerRemoteSync();
    });
  }

  disconnect(): void {
    this.network.disconnect();
    for (const timer of this._syncTimers.values()) clearTimeout(timer);
    this._syncTimers.clear();
    this._closeBroadcast();
  }

  // ── Network state ─────────────────────────────────────────────────────────

  goOffline(): void {
    this._online = false;
    this._log('network_offline', {});
    this.onNetworkState?.(false);
  }

  goOnline(): void {
    this._online = true;
    this._log('network_online', {});
    this.onNetworkState?.(true);
    // Flush any queued sync
    if (this._pendingSync && this._modelId) {
      this._log('flush_queue', { modelId: this._modelId });
      this._pendingSync = false;
      this.syncWithServer();
    }
  }

  get isOnline(): boolean { return this._online; }

  // ── Doc lifecycle ─────────────────────────────────────────────────────────

  /** Create a fresh empty doc. Does not save to storage. */
  async createDoc(modelId: string): Promise<void> {
    this._docBytes = await this.wasm.create_doc();
    this._modelId = modelId;
  }

  /** Load doc from storage. Returns true if found. */
  async loadFromStorage(modelId: string): Promise<boolean> {
    const bytes = await this.storage.load(modelId);
    if (!bytes) {
      this._log('load_storage', { modelId, found: false });
      return false;
    }
    this._docBytes = bytes;
    this._modelId = modelId;
    this._log('load_storage', { modelId, found: true });
    return true;
  }

  /**
   * Load doc from storage and immediately sync with server.
   * Covers the "page closed while offline" case — if a local doc exists,
   * it may have unsent ops. Syncing on load ensures they reach the server.
   *
   * Returns true if a doc was found in storage.
   */
  async loadAndSync(modelId: string): Promise<boolean> {
    const found = await this.loadFromStorage(modelId);
    if (found && this._online) {
      this._log('load_sync', { modelId });
      this.syncWithServer();
    }
    return found;
  }

  /** Adopt externally-provided doc bytes (e.g. from server bootstrap). */
  adoptDoc(modelId: string, bytes: Uint8Array): void {
    this._docBytes = bytes;
    this._modelId = modelId;
  }

  /** Save current doc to storage. */
  async saveToStorage(): Promise<void> {
    if (!this._docBytes || !this._modelId) return;
    await this.storage.save(this._modelId, this._docBytes);
    this._log('save_storage', { modelId: this._modelId });
  }

  /**
   * Reset sync state for a model — clears local doc, storage, and presence.
   * The consuming system calls this for "local reset" (re-sync from server)
   * or before a full delete (after calling its own server DELETE endpoint).
   */
  async reset(modelId?: string): Promise<void> {
    const mid = modelId ?? this._modelId;
    if (mid) {
      await this.storage.delete(mid);
    }
    this._docBytes = null;
    this._modelId = null;
    this._presence.clear();
    this._closeBroadcast();
    for (const timer of this._syncTimers.values()) clearTimeout(timer);
    this._syncTimers.clear();
    this._pendingSync = false;
  }

  // ── Op recording ──────────────────────────────────────────────────────────

  /** Record a completed op into the CRDT doc. */
  async addOp(op: Operation): Promise<void> {
    if (!this._docBytes || !this._modelId) return;
    this._docBytes = await this.wasm.apply_op(this._docBytes, JSON.stringify(op));
    this._log('add_op', { modelId: this._modelId, opType: op.type, opId: op.id });
    await this.saveToStorage();
    this._broadcastDoc();
    this._scheduleSyncIfOnline();
  }

  /** Disable an op by ID (undo). */
  async setOpEnabled(opId: string, enabled: boolean): Promise<void> {
    if (!this._docBytes || !this._modelId) return;
    this._docBytes = await this.wasm.set_op_enabled(this._docBytes, opId, enabled);
    this._log(enabled ? 'redo_op' : 'undo_op', { modelId: this._modelId, opId });
    await this.saveToStorage();
    this._scheduleSyncIfOnline();
  }

  /** Disable all ops in a group. */
  async setGroupEnabled(groupId: string, enabled: boolean): Promise<void> {
    if (!this._docBytes || !this._modelId) return;
    this._docBytes = await this.wasm.set_group_enabled(this._docBytes, groupId, enabled);
    this._log(enabled ? 'redo_group' : 'undo_group', { modelId: this._modelId, groupId });
    await this.saveToStorage();
    this._scheduleSyncIfOnline();
  }

  /** Disable all own ops after toIndex. */
  async rollbackTo(toIndex: number): Promise<void> {
    if (!this._docBytes || !this._modelId) return;
    this._docBytes = await this.wasm.rollback_to(this._docBytes, this.opts.actorId, toIndex);
    this._log('rollback', { modelId: this._modelId, toIndex });
    await this.saveToStorage();
    this._scheduleSyncIfOnline();
  }

  // ── Read state ────────────────────────────────────────────────────────────

  async getOps(): Promise<Operation[]> {
    if (!this._docBytes) return [];
    try { return JSON.parse(await this.wasm.get_ops(this._docBytes)); }
    catch { return []; }
  }

  async getReplayOps(): Promise<Operation[]> {
    if (!this._docBytes) return [];
    try { return JSON.parse(await this.wasm.get_replay_ops(this._docBytes)); }
    catch { return []; }
  }

  async getOpCount(): Promise<number> {
    if (!this._docBytes) return 0;
    try { return await this.wasm.get_op_count(this._docBytes); }
    catch { return 0; }
  }

  async getName(): Promise<string> {
    if (!this._docBytes) return '';
    try { return await this.wasm.get_name(this._docBytes); }
    catch { return ''; }
  }

  async setName(name: string): Promise<void> {
    if (!this._docBytes) return;
    this._docBytes = await this.wasm.set_name(this._docBytes, name);
  }

  get docBytes(): Uint8Array | null { return this._docBytes; }
  get modelId(): string | null { return this._modelId; }
  get actorId(): string { return this.opts.actorId; }

  // ── Incremental sync (G15) ─────────────────────────────────────────────

  /**
   * Get ops added since a given index. Uses WASM export_ops_since for
   * efficient delta extraction without parsing the full op list.
   *
   * Returns JSON string of ops (same format as get_ops).
   * Use this for delta sync: track the last-synced index and only
   * send/process ops after that point.
   */
  async getOpsSince(sinceIndex: number): Promise<Operation[]> {
    if (!this._docBytes) return [];
    try {
      const json = await this.wasm.get_ops(this._docBytes);
      const all: Operation[] = JSON.parse(json);
      return all.slice(sinceIndex);
    } catch { return []; }
  }

  async canUndo(): Promise<boolean> {
    return (await this.getOps()).some(op => op.actorId === this.opts.actorId && op.enabled);
  }

  async canRedo(): Promise<boolean> {
    const ops = await this.getOps();
    let foundDisabled = false;
    for (let i = ops.length - 1; i >= 0; i--) {
      if (ops[i].actorId === this.opts.actorId) {
        if (!ops[i].enabled) foundDisabled = true;
        else break;
      }
    }
    return foundDisabled;
  }

  // ── Server sync ───────────────────────────────────────────────────────────

  /** Push local doc to server, merge returned doc, return whether new ops arrived. */
  async syncWithServer(): Promise<{ hadNewOps: boolean }> {
    if (!this._docBytes || !this._modelId || this._syncing) {
      return { hadNewOps: false };
    }
    if (!this._online) {
      this._pendingSync = true;
      this._log('queue_op', { modelId: this._modelId, reason: 'offline' });
      return { hadNewOps: false };
    }

    this._syncing = true;
    this._log('sync_start', { modelId: this._modelId });

    try {
      const serverDoc = await this._postSyncWithRetry();

      if (!serverDoc) {
        this._log('sync_error', { modelId: this._modelId, reason: 'no response after retries' });
        return { hadNewOps: false };
      }

      // Blake3 hash-based change detection (ADR-0008 Phase 4)
      const hashBefore = await this.wasm.doc_hash(this._docBytes);
      this._docBytes = await this.wasm.merge_docs(this._docBytes, serverDoc);
      const hashAfter = await this.wasm.doc_hash(this._docBytes);
      const hadNewOps = hashBefore !== hashAfter;

      this._log('merge', {
        modelId: this._modelId,
        hadNewOps,
        hashBefore: hashBefore.slice(0, 12),
        hashAfter: hashAfter.slice(0, 12),
        source: 'server',
      });

      await this.saveToStorage();
      this.onSyncComplete?.(hadNewOps);

      if (hadNewOps) {
        // Can't slice by old count since we use hash-based detection now —
        // emit all ops and let the consumer diff if needed
        const allOps = await this.getOps();
        this.onRemoteOps?.(allOps);
      }

      this._log('sync_complete', { modelId: this._modelId, hadNewOps });
      return { hadNewOps };

    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      this._log('sync_error', { modelId: this._modelId, error: message });
      this.onError?.(err instanceof Error ? err : new Error(message), 'syncWithServer');
      return { hadNewOps: false };
    } finally {
      this._syncing = false;
    }
  }

  /** Post sync with exponential backoff retry. Returns null if all attempts fail. */
  private async _postSyncWithRetry(): Promise<Uint8Array | null> {
    const maxAttempts = 1 + this._maxRetries; // 1 initial + retries
    for (let attempt = 0; attempt < maxAttempts; attempt++) {
      const result = await this.network.postSync(
        this._modelId!,
        this._docBytes!,
        this.opts.actorId,
      );
      if (result) return result;

      // No response — retry if attempts remain
      if (attempt < maxAttempts - 1) {
        const delayMs = this._retryBaseMs * Math.pow(2, attempt); // 1s, 2s, 4s
        this._log('sync_retry', {
          modelId: this._modelId,
          attempt: attempt + 1,
          maxRetries: this._maxRetries,
          delayMs,
        });
        await new Promise(r => setTimeout(r, delayMs));
        // Abort retry if we went offline during the wait
        if (!this._online) return null;
      }
    }
    return null;
  }

  // ── BroadcastChannel (G11) ────────────────────────────────────────────────

  /**
   * Open a BroadcastChannel for cross-tab sync.
   * Call after createDoc or loadFromStorage. Tab A's addOp instantly
   * propagates to Tab B without a server round-trip.
   *
   * @param channelName — default: `plat-sync:${modelId}`
   */
  openBroadcast(channelName?: string): void {
    if (!this._modelId) return;
    this._closeBroadcast();
    const name = channelName ?? `plat-sync:${this._modelId}`;
    // Use globalThis to avoid shadowing the real browser global with our type stub
    const BC = (globalThis as any).BroadcastChannel;
    if (!BC) return; // not available (e.g. CF Workers)
    this._broadcast = new BC(name) as BroadcastChannelLike;
    this._broadcast.onmessage = (e: MessageEvent) => {
      const msg = e.data as SyncMessage;
      if (msg.type !== 'doc_update') return;
      if (msg.tabId === this.tabId) return; // ignore own messages
      if (msg.modelId !== this._modelId) return;
      this._log('broadcast_receive', { modelId: msg.modelId, fromTab: msg.tabId });
      this._mergeRemoteBytes(new Uint8Array(msg.bytes));
    };
  }

  private _closeBroadcast(): void {
    if (this._broadcast) {
      this._broadcast.close();
      this._broadcast = null;
    }
  }

  private _broadcastDoc(): void {
    if (!this._broadcast || !this._docBytes || !this._modelId) return;
    const msg: SyncMessage = {
      type: 'doc_update',
      modelId: this._modelId,
      bytes: Array.from(this._docBytes),
      tabId: this.tabId,
    };
    this._broadcast.postMessage(msg);
    this._log('broadcast_send', { modelId: this._modelId });
  }

  private async _mergeRemoteBytes(remote: Uint8Array): Promise<void> {
    if (!this._docBytes) return;
    const hashBefore = await this.wasm.doc_hash(this._docBytes);
    this._docBytes = await this.wasm.merge_docs(this._docBytes, remote);
    const hashAfter = await this.wasm.doc_hash(this._docBytes);
    const hadNewOps = hashBefore !== hashAfter;
    if (hadNewOps) {
      await this.saveToStorage();
      this._log('merge', { modelId: this._modelId, hadNewOps, source: 'broadcast' });
      const allOps = await this.getOps();
      this.onRemoteOps?.(allOps);
    }
  }

  // ── Presence (G14) ──────────────────────────────────────────────────────

  /** Update local presence state and notify listeners. */
  setPresence(state: Omit<PresenceState, 'actorId'>): void {
    const full: PresenceState = { ...state, actorId: this.opts.actorId };
    this._presence.set(this.opts.actorId, full);
    this._log('presence_update', { actorId: this.opts.actorId });
    this.onPresence?.(this.getPresence());
  }

  /** Receive presence from a remote actor (e.g. from SSE). */
  updateRemotePresence(state: PresenceState): void {
    this._presence.set(state.actorId, state);
    this.onPresence?.(this.getPresence());
  }

  /** Remove a remote actor's presence (e.g. on disconnect). */
  removePresence(actorId: string): void {
    this._presence.delete(actorId);
    this.onPresence?.(this.getPresence());
  }

  /** Get all known presence states. */
  getPresence(): PresenceState[] {
    return Array.from(this._presence.values());
  }

  // ── Storage budget / compaction (G16) ──────────────────────────────────

  /**
   * Check doc size and compact if over budget.
   * Automerge's save() already produces a compacted binary.
   * Call this periodically or after large merges.
   *
   * Returns the new doc size, or 0 if no doc loaded.
   */
  async compactIfNeeded(): Promise<number> {
    if (!this._docBytes || !this._modelId) return 0;
    if (this._maxDocBytes <= 0) return this._docBytes.length; // no limit set
    if (this._docBytes.length <= this._maxDocBytes) return this._docBytes.length;

    // Re-save through WASM — Automerge compacts on save
    // The simplest compaction: re-create by merging doc with an empty doc
    const empty = await this.wasm.create_doc();
    this._docBytes = await this.wasm.merge_docs(empty, this._docBytes);
    await this.saveToStorage();
    this._log('compact', {
      modelId: this._modelId,
      newSize: this._docBytes.length,
      budget: this._maxDocBytes,
    });
    return this._docBytes.length;
  }

  /** Current doc size in bytes, or 0 if no doc loaded. */
  get docSize(): number {
    return this._docBytes?.length ?? 0;
  }

  /** Blake3 hash of current doc bytes — for change detection and integrity checks. */
  async docHash(): Promise<string> {
    if (!this._docBytes) return '';
    return this.wasm.doc_hash(this._docBytes);
  }

  // ── Internal ──────────────────────────────────────────────────────────────

  private _scheduleSyncIfOnline(): void {
    if (!this._online) {
      this._pendingSync = true;
      return;
    }
    const modelId = this._modelId;
    if (!modelId) return;
    // Per-model debounce (G17) — each model gets its own timer
    const existing = this._syncTimers.get(modelId);
    if (existing) clearTimeout(existing);
    this._syncTimers.set(modelId, setTimeout(() => {
      this._syncTimers.delete(modelId);
      this.syncWithServer();
    }, this._debounceMs));
  }

  private _triggerRemoteSync(): void {
    // Remote change arrived — sync immediately (cancel debounce for this model)
    if (this._modelId) {
      const existing = this._syncTimers.get(this._modelId);
      if (existing) {
        clearTimeout(existing);
        this._syncTimers.delete(this._modelId);
      }
    }
    this._activeSyncPromise = this.syncWithServer().then(() => {
      this._activeSyncPromise = null;
    });
  }

  /**
   * Resolves when any in-progress sync triggered by a remote change completes.
   * Useful in tests: await client.waitForSync() after triggerRemoteChange().
   */
  async waitForSync(): Promise<void> {
    if (this._activeSyncPromise) await this._activeSyncPromise;
  }

  private _log(event: SyncEventType, detail: Record<string, unknown>): void {
    const entry: SyncLogEntry = {
      ts: Date.now(),
      modelId: this._modelId ?? '',
      actorId: this.opts.actorId,
      event,
      detail,
    };
    this.syncLog.push(entry);
    // Trim to max
    if (this.syncLog.length > this._maxLog) {
      this.syncLog.splice(0, this.syncLog.length - this._maxLog);
    }
    // Structured console output — assertable in tests
    console.log(`[sync:${event}]`, JSON.stringify(detail));
  }
}

// ── Browser network state binding ──────────────────────────────────────────

/**
 * Bind a SyncClient to the browser's online/offline events.
 * Sets initial state from `navigator.onLine` and auto-calls
 * `goOnline()` / `goOffline()` on connectivity changes.
 *
 * Returns a cleanup function that removes the listeners.
 *
 * Usage (browser only):
 *   const unbind = bindNetworkEvents(client);
 *   // later: unbind();
 */
export function bindNetworkEvents(client: SyncClient): () => void {
  const g = globalThis as any;
  // Set initial state
  if (g.navigator && !g.navigator.onLine) {
    client.goOffline();
  }

  const onOnline = () => client.goOnline();
  const onOffline = () => client.goOffline();

  if (g.window) {
    g.window.addEventListener('online', onOnline);
    g.window.addEventListener('offline', onOffline);
  }

  return () => {
    if (g.window) {
      g.window.removeEventListener('online', onOnline);
      g.window.removeEventListener('offline', onOffline);
    }
  };
}
