// systems/auth/worker/src/db/auth.schema.ts
//
// AUTO-GENERATED by better-auth CLI. Do not edit by hand.
// Regenerate: bun run auth:generate
//
// Run after any auth config change:
//   bun run auth:generate
//   bun run auth:migrate:local   # local D1
//   bun run auth:migrate:prod    # Cloudflare D1

// Placeholder — will be populated on first `bun run auth:generate`
export {};
