// systems/auth/worker/src/db/auth.schema.ts
//
// AUTO-GENERATED by better-auth CLI.
// Run: bun run auth:generate   (MacBook — needs network for npx auth@latest)
// OR:  POST /auth/migrate      (programmatic — works in CF Workers, no CLI needed)
//
// Do not edit by hand — regenerate after any plugin change.
export {};
