// Generated by dev/gen-types.ts — do not edit.
// Source: crate/src/types.rs
// Re-generate: bun run gen:types
// Check:       bun run check:types

type LogLevel = "debug" | "info" | "warn" | "error";

type LogKind = "http" | "app" | "error";

type LogEntry = { ts: string, level: LogLevel, kind: LogKind, source: string, system: string, event: string, service?: string, env?: string, traceId?: string, spanId?: string, requestId?: string, error?: string, stack?: string, method?: string, path?: string, status?: number, durationMs?: number, cfRay?: string, cfColo?: string, ip?: string, userAgent?: string, };

type EntryFilter = { source?: string, system?: string, kind?: LogKind, level?: LogLevel, event?: string, 
/**
 * ISO timestamp — return entries with ts >= since
 */
since?: string, limit?: number, };
