// Generated by dev/gen-wasm.ts — do not edit.
// Source: crate/pkg/plat_observe.d.ts [2d0504766dd1]
// Re-generate: bun dev/gen-wasm.ts
// Check:       bun dev/gen-wasm.ts --check

/**
 * Typed WASM loader for lib/observe/crate.
 *
 * Works in three runtimes:
 *   Wrangler (CF Worker + dev) — default import is WebAssembly.Module → instantiate with glue
 *   Bun dev server             — default import is file path string → Bun.file().arrayBuffer()
 *   vitest (vite-plugin-wasm)  — namespace already has instantiated exports
 */

// ── Generated interface (from crate/pkg/plat_observe.d.ts) ──────────────────────

export interface ObserveWasm {
  /**
 * Format a W3C traceparent header value from two u64 halves of the trace ID and a span ID.
 * Returns "00-{trace_id}-{span_id}-01"
   */
  format_traceparent(trace_hi: bigint, trace_lo: bigint, span_id: bigint): string
  /**
 * Returns the crate version — used by the demo to verify the WASM loaded correctly.
   */
  observe_version(): string
  /**
 * Parse a W3C traceparent header and extract the trace ID (32 hex chars).
 * Returns an empty string if the header is invalid.
   */
  parse_trace_id(traceparent: string): string
  /**
 * Decide whether to keep a log entry based on sampling rate and a seed value.
 * Deterministic: same (rate, seed) always returns the same result.
   */
  sample_keep(rate: number, seed: number): boolean
  /**
 * Scrub a JSON log entry string: redact values for any sensitive keys.
 * Returns the scrubbed JSON string. Invalid JSON is returned unchanged.
   */
  scrub_entry(json: string): string
}

// ── Imports ───────────────────────────────────────────────────────────────────

import wasmDefault from '../crate/pkg/plat_observe_bg.wasm'
import * as wasmStar  from '../crate/pkg/plat_observe_bg.wasm'
// @ts-expect-error — no .d.ts for the bg.js glue (generated code)
import * as bg from '../crate/pkg/plat_observe_bg.js'

// ── Loader (lazy singleton) ───────────────────────────────────────────────────

let _initialized = false

export async function loadObserveWasm(): Promise<ObserveWasm> {
  if (_initialized) return bg as unknown as ObserveWasm

  const glueImports = buildGlueImports()

  if (wasmDefault instanceof WebAssembly.Module) {
    // Wrangler / CF Worker: default import is a compiled WebAssembly.Module
    const instance = await WebAssembly.instantiate(wasmDefault, {
      './plat_observe_bg.js': glueImports,
    })
    bg.__wbg_set_wasm(instance.exports)
    ;(instance.exports as unknown as { __wbindgen_start(): void }).__wbindgen_start()

  } else if (typeof wasmDefault === 'string') {
    // Bun dev server: default import is the file path — read bytes then instantiate
    const bytes = await Bun.file(wasmDefault).arrayBuffer()
    const result = await WebAssembly.instantiate(bytes, {
      './plat_observe_bg.js': glueImports,
    })
    const inst = (result as unknown as WebAssembly.WebAssemblyInstantiatedSource).instance
    bg.__wbg_set_wasm(inst.exports)
    ;(inst.exports as unknown as { __wbindgen_start(): void }).__wbindgen_start()

  } else {
    // vitest (vite-plugin-wasm): namespace has already-instantiated exports
    bg.__wbg_set_wasm(wasmStar as unknown as WebAssembly.Exports)
  }

  _initialized = true
  return bg as unknown as ObserveWasm
}

function buildGlueImports(): WebAssembly.ModuleImports {
  const imports: WebAssembly.ModuleImports = {}
  for (const [key, value] of Object.entries(bg)) {
    if (typeof value === 'function') {
      imports[key] = value as WebAssembly.ImportValue
    }
  }
  return imports
}

// ── Convenience helpers ───────────────────────────────────────────────────────

/** Scrub a log entry object. Returns a new object with sensitive values redacted. */
export async function scrubEntry(entry: Record<string, unknown>): Promise<Record<string, unknown>> {
  const wasm = await loadObserveWasm()
  return JSON.parse(wasm.scrub_entry(JSON.stringify(entry)))
}

/** Decide whether to keep a log entry. seed should be a stable per-request value. */
export async function sampleKeep(rate: number, seed: number): Promise<boolean> {
  const wasm = await loadObserveWasm()
  return wasm.sample_keep(rate, seed)
}
