#!/usr/bin/env bun
/**
 * dev/gen-openapi.ts — Generate shared/openapi.json from shared/schemas.json
 *
 * Builds a full OpenAPI 3.0 spec for the observe log API routes.
 * Schemas reference the same definitions generated by schemars from Rust structs.
 *
 * Usage:
 *   bun dev/gen-openapi.ts           # generate shared/openapi.json
 *   bun dev/gen-openapi.ts --check   # verify up-to-date (CI)
 */

import { readFileSync, writeFileSync, existsSync } from 'fs'
import { createHash } from 'crypto'

const SCHEMA_PATH = 'shared/schemas.json'
const OUT_PATH    = 'shared/openapi.json'

const schemas = JSON.parse(readFileSync(SCHEMA_PATH, 'utf-8'))
const defs = schemas.definitions
const schemaHash = createHash('sha256').update(JSON.stringify(defs)).digest('hex').slice(0, 12)

// Map schemars Draft-07 definitions → OpenAPI 3.0 components/schemas
// (rename `definitions` → `components/schemas`, fix $ref paths)
function fixRefs(obj: any): any {
  if (typeof obj !== 'object' || obj === null) return obj
  if (Array.isArray(obj)) return obj.map(fixRefs)
  const out: any = {}
  for (const [k, v] of Object.entries(obj)) {
    if (k === '$ref' && typeof v === 'string') {
      out[k] = (v as string).replace('#/definitions/', '#/components/schemas/')
    } else {
      out[k] = fixRefs(v)
    }
  }
  return out
}

const components: Record<string, any> = {}
for (const [name, def] of Object.entries(defs)) {
  components[name] = fixRefs(def)
}

// ── Shared query param definitions ────────────────────────────────────────────

const filterParams = [
  { name: 'source', in: 'query', schema: { type: 'string' }, description: 'Filter by log source (browser, worker, ...)' },
  { name: 'system', in: 'query', schema: { type: 'string' }, description: 'Filter by subsystem name' },
  { name: 'kind',   in: 'query', schema: { '$ref': '#/components/schemas/LogKind' }, description: 'Filter by entry kind' },
  { name: 'level',  in: 'query', schema: { '$ref': '#/components/schemas/LogLevel' }, description: 'Minimum log level' },
  { name: 'event',  in: 'query', schema: { type: 'string' }, description: 'Filter by event name' },
  { name: 'since',  in: 'query', schema: { type: 'string', format: 'date-time' }, description: 'Return entries with ts >= since (ISO 8601)' },
  { name: 'limit',  in: 'query', schema: { type: 'integer', minimum: 1, maximum: 1000 }, description: 'Max entries to return' },
]

const spec = {
  openapi: '3.0.0',
  info: {
    title: 'plat-observe API',
    version: '0.1.0',
    description: 'Structured log buffer API for CF Workers and Bun. Schema generated from Rust structs via schemars.',
  },
  tags: [
    { name: 'logs', description: 'Log buffer operations' },
    { name: 'mcp',  description: 'Model Context Protocol — AI agent access to logs' },
  ],
  components: {
    schemas: components,
  },
  paths: {
    '/api/debug/logs': {
      get: {
        tags: ['logs'],
        summary: 'Query log entries',
        description: 'Return buffered log entries with optional filters.',
        parameters: filterParams,
        responses: {
          '200': {
            description: 'Filtered log entries',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    count:   { type: 'integer' },
                    entries: { type: 'array', items: { '$ref': '#/components/schemas/LogEntry' } },
                  },
                },
              },
            },
          },
        },
      },
      delete: {
        tags: ['logs'],
        summary: 'Clear log buffer',
        responses: {
          '200': {
            description: 'Buffer cleared',
            content: { 'application/json': { schema: { type: 'object', properties: { cleared: { type: 'boolean' } } } } },
          },
        },
      },
    },

    '/api/debug/logs/ingest': {
      post: {
        tags: ['logs'],
        summary: 'Ingest log entries (browser → worker flush)',
        description: 'Accepts an array of LogEntry objects. Each entry is validated against the Rust-derived schema before ingestion.',
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: { type: 'array', items: { '$ref': '#/components/schemas/LogEntry' } },
            },
          },
        },
        responses: {
          '200': {
            description: 'Entries ingested',
            content: { 'application/json': { schema: { type: 'object', properties: { ingested: { type: 'integer' } } } } },
          },
          '400': {
            description: 'Invalid entries',
            content: { 'application/json': { schema: { type: 'object', properties: { error: { type: 'string' }, issues: { type: 'array' } } } } },
          },
        },
      },
    },

    '/api/debug/logs/tail': {
      get: {
        tags: ['logs'],
        summary: 'SSE log tail (real-time stream)',
        description: 'Server-Sent Events stream of new log entries. CF Workers safe (poll-based, no setInterval).',
        parameters: filterParams,
        responses: {
          '200': {
            description: 'SSE stream of LogEntry objects',
            content: { 'text/event-stream': { schema: { type: 'string' } } },
          },
        },
      },
    },

    '/api/debug/logs/urls': {
      get: {
        tags: ['logs'],
        summary: 'Get all log URL endpoints',
        description: 'Returns local, production, and Cloudflare dashboard URLs. Useful for scripts and AI agents.',
        responses: {
          '200': { description: 'URL map', content: { 'application/json': { schema: { type: 'object' } } } },
        },
      },
    },

    '/mcp': {
      post: {
        tags: ['mcp'],
        summary: 'Model Context Protocol endpoint',
        description: [
          'JSON-RPC 2.0 endpoint for AI agents (Claude, Gemini, Cursor).',
          '',
          'Methods: `initialize`, `tools/list`, `tools/call`',
          '',
          'Tools: `query_logs` (EntryFilter), `get_trace` (traceId), `get_stats`, `clear_logs`',
          '',
          'Tool inputSchemas are derived from Rust structs via schemars — same source as this spec.',
        ].join('\n'),
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                type: 'object',
                required: ['jsonrpc', 'id', 'method'],
                properties: {
                  jsonrpc: { type: 'string', enum: ['2.0'] },
                  id:      { oneOf: [{ type: 'string' }, { type: 'integer' }] },
                  method:  { type: 'string', enum: ['initialize', 'tools/list', 'tools/call'] },
                  params:  { type: 'object' },
                },
              },
            },
          },
        },
        responses: {
          '200': { description: 'JSON-RPC 2.0 response', content: { 'application/json': { schema: { type: 'object' } } } },
        },
      },
    },
  },
}

const out = JSON.stringify(spec, null, 2) + '\n'

const check = process.argv.includes('--check')

if (check) {
  let current = ''
  try { current = readFileSync(OUT_PATH, 'utf-8') } catch {}
  if (current === out) {
    console.log(`✓ ${OUT_PATH} is up-to-date [${schemaHash}]`)
    process.exit(0)
  } else {
    console.error(`✗ ${OUT_PATH} is stale — run: bun dev/gen-openapi.ts`)
    process.exit(1)
  }
}

writeFileSync(OUT_PATH, out)
console.log(`✓ ${OUT_PATH} generated [${schemaHash}] — ${Object.keys(spec.paths).length} paths`)
