#!/usr/bin/env bun
/**
 * dev/gen-wasm.ts — Generate shared/wasm.generated.ts from crate/pkg/plat_observe.d.ts
 *
 * Reads the wasm-pack .d.ts (source of truth — produced directly from Rust #[wasm_bindgen])
 * and emits a typed WASM loader that works across all three runtimes:
 *   Wrangler (CF Worker)  — default import is WebAssembly.Module
 *   Bun dev server        — default import is file path string
 *   vitest                — namespace already has instantiated exports
 *
 * Usage:
 *   bun dev/gen-wasm.ts           # generate shared/wasm.generated.ts
 *   bun dev/gen-wasm.ts --check   # verify generated file is up-to-date (CI)
 */

import { readFileSync, writeFileSync } from 'fs'
import { createHash } from 'crypto'

const DTS_PATH = 'crate/pkg/plat_observe.d.ts'
const OUT_PATH = 'shared/wasm.generated.ts'

// ── Parse .d.ts → function signatures ────────────────────────────────────────

const dts = readFileSync(DTS_PATH, 'utf-8')
const dtsHash = createHash('sha256').update(dts).digest('hex').slice(0, 12)

// Extract `export function name(params): return;` lines with preceding JSDoc
const fnRegex = /(?:\/\*\*[\s\S]*?\*\/\n)?export function (\w+)\(([^)]*)\): ([^;]+);/g
const fns: Array<{ name: string; params: string; ret: string; doc: string }> = []

let match
while ((match = fnRegex.exec(dts)) !== null) {
  const fullMatch = match[0]
  const docMatch = fullMatch.match(/\/\*\*([\s\S]*?)\*\//)
  const doc = docMatch
    ? docMatch[1].trim().split('\n').map(l => ' * ' + l.replace(/^\s*\*?\s?/, '')).join('\n')
    : ''
  fns.push({ name: match[1], params: match[2], ret: match[3].trim(), doc })
}

if (fns.length === 0) {
  console.error(`ERROR: no exported functions found in ${DTS_PATH}`)
  process.exit(1)
}

// ── Emit typed interface ──────────────────────────────────────────────────────

const ifaceLines = fns.map(f => {
  const comment = f.doc ? `  /**\n${f.doc}\n   */\n` : ''
  return `${comment}  ${f.name}(${f.params}): ${f.ret}`
})

// ── Emit full generated file ──────────────────────────────────────────────────

const out = `\
// Generated by dev/gen-wasm.ts — do not edit.
// Source: ${DTS_PATH} [${dtsHash}]
// Re-generate: bun dev/gen-wasm.ts
// Check:       bun dev/gen-wasm.ts --check

/**
 * Typed WASM loader for lib/observe/crate.
 *
 * Works in three runtimes:
 *   Wrangler (CF Worker + dev) — default import is WebAssembly.Module → instantiate with glue
 *   Bun dev server             — default import is file path string → Bun.file().arrayBuffer()
 *   vitest (vite-plugin-wasm)  — namespace already has instantiated exports
 */

// ── Generated interface (from ${DTS_PATH}) ──────────────────────

export interface ObserveWasm {
${ifaceLines.join('\n')}
}

// ── Imports ───────────────────────────────────────────────────────────────────

import wasmDefault from '../crate/pkg/plat_observe_bg.wasm'
import * as wasmStar  from '../crate/pkg/plat_observe_bg.wasm'
// @ts-expect-error — no .d.ts for the bg.js glue (generated code)
import * as bg from '../crate/pkg/plat_observe_bg.js'

// ── Loader (lazy singleton) ───────────────────────────────────────────────────

let _initialized = false

export async function loadObserveWasm(): Promise<ObserveWasm> {
  if (_initialized) return bg as unknown as ObserveWasm

  const glueImports = buildGlueImports()

  if (wasmDefault instanceof WebAssembly.Module) {
    // Wrangler / CF Worker: default import is a compiled WebAssembly.Module
    const instance = await WebAssembly.instantiate(wasmDefault, {
      './plat_observe_bg.js': glueImports,
    })
    bg.__wbg_set_wasm(instance.exports)
    ;(instance.exports as unknown as { __wbindgen_start(): void }).__wbindgen_start()

  } else if (typeof wasmDefault === 'string') {
    // Bun dev server: default import is the file path — read bytes then instantiate
    const bytes = await Bun.file(wasmDefault).arrayBuffer()
    const result = await WebAssembly.instantiate(bytes, {
      './plat_observe_bg.js': glueImports,
    })
    const inst = (result as unknown as WebAssembly.WebAssemblyInstantiatedSource).instance
    bg.__wbg_set_wasm(inst.exports)
    ;(inst.exports as unknown as { __wbindgen_start(): void }).__wbindgen_start()

  } else {
    // vitest (vite-plugin-wasm): namespace has already-instantiated exports
    bg.__wbg_set_wasm(wasmStar as unknown as WebAssembly.Exports)
  }

  _initialized = true
  return bg as unknown as ObserveWasm
}

function buildGlueImports(): WebAssembly.ModuleImports {
  const imports: WebAssembly.ModuleImports = {}
  for (const [key, value] of Object.entries(bg)) {
    if (typeof value === 'function') {
      imports[key] = value as WebAssembly.ImportValue
    }
  }
  return imports
}

// ── Convenience helpers ───────────────────────────────────────────────────────

/** Scrub a log entry object. Returns a new object with sensitive values redacted. */
export async function scrubEntry(entry: Record<string, unknown>): Promise<Record<string, unknown>> {
  const wasm = await loadObserveWasm()
  return JSON.parse(wasm.scrub_entry(JSON.stringify(entry)))
}

/** Decide whether to keep a log entry. seed should be a stable per-request value. */
export async function sampleKeep(rate: number, seed: number): Promise<boolean> {
  const wasm = await loadObserveWasm()
  return wasm.sample_keep(rate, seed)
}
`

// ── Write or check ────────────────────────────────────────────────────────────

const check = process.argv.includes('--check')

if (check) {
  let current: string
  try { current = readFileSync(OUT_PATH, 'utf-8') } catch { current = '' }
  if (current === out) {
    console.log(`✓ ${OUT_PATH} is up-to-date [${dtsHash}]`)
    process.exit(0)
  } else {
    console.error(`✗ ${OUT_PATH} is stale — run: bun dev/gen-wasm.ts`)
    process.exit(1)
  }
}

writeFileSync(OUT_PATH, out)
console.log(`✓ ${OUT_PATH} generated [${dtsHash}] — ${fns.length} exports: ${fns.map(f => f.name).join(', ')}`)
