#!/usr/bin/env bun
/**
 * dev/gen-zod.ts — Generate shared/schemas.zod.ts from shared/schemas.json
 *
 * Reads the schemars-generated JSON Schema (source of truth from Rust structs)
 * and emits typed Zod validators for runtime validation in CF Workers + Bun.
 *
 * Why Zod from JSON Schema (not hand-written)?
 *   The JSON Schema is auto-generated from Rust — it's the canonical source.
 *   Zod derived from it stays in sync automatically when Rust types change.
 *   Workflow: change Rust → bun run gen:types → bun run gen:zod → updated validators
 *
 * Usage:
 *   bun dev/gen-zod.ts           # generate shared/schemas.zod.ts
 *   bun dev/gen-zod.ts --check   # verify generated file is up-to-date (CI)
 */

import { readFileSync, writeFileSync, existsSync } from 'fs'
import { createHash } from 'crypto'

const SCHEMA_PATH = 'shared/schemas.json'
const OUT_PATH    = 'shared/schemas.zod.ts'

const schemas = JSON.parse(readFileSync(SCHEMA_PATH, 'utf-8'))
const defs: Record<string, any> = schemas.definitions
const schemaHash = createHash('sha256').update(JSON.stringify(defs)).digest('hex').slice(0, 12)

// ── Convert a JSON Schema node to a Zod expression ───────────────────────────

function toZod(schema: any, required = true): string {
  // $ref → reference to a named schema
  if (schema.$ref) {
    const name = schema.$ref.replace('#/definitions/', '')
    const ref = `${name}Schema`
    return required ? ref : `${ref}.nullish()`
  }

  // anyOf / oneOf — schemars uses this for Option<Enum>: [{$ref}, {type:"null"}]
  const variants: any[] = schema.anyOf ?? schema.oneOf ?? []
  if (variants.length > 0) {
    const nonNull = variants.filter((s: any) => s.type !== 'null')
    const isNullable = variants.length > nonNull.length
    if (nonNull.length === 1) {
      const inner = toZod(nonNull[0], true)
      if (isNullable && !required) return `${inner}.nullish()`
      if (isNullable)              return `${inner}.nullable()`
      if (!required)               return `${inner}.optional()`
      return inner
    }
    return 'z.unknown()'
  }

  // Enum → z.enum([...])
  if (schema.enum) {
    return `z.enum(${JSON.stringify(schema.enum)} as const)`
  }

  // Normalise type to array
  const types: string[] = Array.isArray(schema.type) ? schema.type : [schema.type ?? 'unknown']
  const nullable = types.includes('null')
  const main = types.find(t => t !== 'null') ?? 'unknown'

  let base: string
  switch (main) {
    case 'string':  base = 'z.string()'; break
    case 'integer': base = 'z.number().int()'; break
    case 'number':  base = 'z.number()'; break
    case 'boolean': base = 'z.boolean()'; break
    case 'object':  base = objectToZod(schema); break
    default:        base = 'z.unknown()'
  }

  if (nullable && !required) return `${base}.nullish()`
  if (nullable)              return `${base}.nullable()`
  if (!required)             return `${base}.optional()`
  return base
}

function objectToZod(schema: any): string {
  const props: Record<string, any> = schema.properties ?? {}
  const req = new Set<string>(schema.required ?? [])
  const fields = Object.entries(props)
    .map(([k, v]) => `  ${k}: ${toZod(v as any, req.has(k))},`)
    .join('\n')
  // .passthrough() preserves unknown keys — LogEntry is an open type ([key: string]: unknown)
  return `z.object({\n${fields}\n}).passthrough()`
}

// ── Collect enum definitions first (others may reference them) ────────────────

const enumNames: string[] = []
const objectNames: string[] = []

for (const [name, def] of Object.entries(defs)) {
  if ((def as any).enum) enumNames.push(name)
  else objectNames.push(name)
}

// ── Emit file ─────────────────────────────────────────────────────────────────

const lines: string[] = [
  `// Generated by dev/gen-zod.ts — do not edit.`,
  `// Source: ${SCHEMA_PATH} [${schemaHash}]`,
  `// Re-generate: bun run gen:zod`,
  `// Check:       bun run check:zod`,
  ``,
  `import { z } from 'zod'`,
  ``,
  `// ── Enums ─────────────────────────────────────────────────────────────────────`,
]

for (const name of enumNames) {
  lines.push(``, `export const ${name}Schema = ${toZod(defs[name])};`)
  lines.push(`export type ${name} = z.infer<typeof ${name}Schema>`)
}

lines.push(``, `// ── Objects ───────────────────────────────────────────────────────────────────`)

for (const name of objectNames) {
  lines.push(``, `export const ${name}Schema = ${toZod(defs[name])};`)
  lines.push(`export type ${name} = z.infer<typeof ${name}Schema>`)
}

lines.push(``, `// ── Array helpers ────────────────────────────────────────────────────────────`)
lines.push(``, `export const LogEntryArraySchema = z.array(LogEntrySchema)`)
lines.push(`export type LogEntryArray = z.infer<typeof LogEntryArraySchema>`)

const out = lines.join('\n') + '\n'

// ── Write or check ────────────────────────────────────────────────────────────

const check = process.argv.includes('--check')

if (check) {
  let current = ''
  try { current = readFileSync(OUT_PATH, 'utf-8') } catch {}
  if (current === out) {
    console.log(`✓ ${OUT_PATH} is up-to-date [${schemaHash}]`)
    process.exit(0)
  } else {
    console.error(`✗ ${OUT_PATH} is stale — run: bun dev/gen-zod.ts`)
    process.exit(1)
  }
}

writeFileSync(OUT_PATH, out)
console.log(`✓ ${OUT_PATH} generated [${schemaHash}]`)
