// Generated by gen-adapters.ts (ADR-0004 Phase 0) — do not edit.
// Source: cad-schema.json boundaries [588b1e6aaa9e]
// Target: native

//! Generated command metadata for native Rust targets (ADR-0004).
//!
//! Provides: command names, domain routing, sync module exports.
//! Use via `include!("commands_generated.rs")` or as a standalone module.

/// All 43 command names from cad-schema.json.
pub const COMMAND_NAMES: &[&str] = &[
    "add_brep",
    "add_cube",
    "add_cylinder",
    "add_sphere",
    "add_torus",
    "begin_sketch",
    "boolean_intersect",
    "boolean_subtract",
    "boolean_union",
    "clash_detect",
    "clear",
    "delete",
    "deselect",
    "duplicate",
    "export_obj",
    "export_scene",
    "export_step",
    "export_stl",
    "get_bim_metadata",
    "get_object_style",
    "get_state",
    "import_ifc",
    "import_scene",
    "import_step",
    "pick_at",
    "pick_mesh_stats",
    "quick_rect_extrude",
    "rename",
    "rotate",
    "scale",
    "select",
    "select_at",
    "set_camera",
    "set_color",
    "set_style",
    "sketch_add_constraint",
    "sketch_add_edge",
    "sketch_add_point",
    "sketch_cancel",
    "sketch_export",
    "sketch_extrude",
    "sketch_solve",
    "translate",
];

/// Command domain categories.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CadDomain {
    Booleans,
    Geometry,
    Scene,
    Sketch,
    Style,
}

/// Look up the domain for a command name.
pub fn command_domain(cmd: &str) -> Option<CadDomain> {
    match cmd {
        "boolean_intersect" | "boolean_subtract" | "boolean_union" | "clash_detect" => Some(CadDomain::Booleans),
        "add_brep" | "add_cube" | "add_cylinder" | "add_sphere" | "add_torus" | "duplicate" | "rotate" | "scale" | "translate" => Some(CadDomain::Geometry),
        "clear" | "delete" | "deselect" | "export_obj" | "export_scene" | "export_step" | "export_stl" | "import_ifc" | "import_scene" | "import_step" | "pick_at" | "select" | "select_at" => Some(CadDomain::Scene),
        "begin_sketch" | "quick_rect_extrude" | "sketch_add_constraint" | "sketch_add_edge" | "sketch_add_point" | "sketch_cancel" | "sketch_export" | "sketch_extrude" | "sketch_solve" => Some(CadDomain::Sketch),
        "get_bim_metadata" | "get_object_style" | "get_state" | "pick_mesh_stats" | "rename" | "set_camera" | "set_color" | "set_style" => Some(CadDomain::Style),
        _ => None,
    }
}

/// All 14 exports from the truck-sync WASM module.
pub const SYNC_EXPORTS: &[&str] = &[
    "create_doc",
    "apply_op",
    "merge_docs",
    "merge_docs_with_info",
    "get_ops",
    "get_op_count",
    "set_op_enabled",
    "set_group_enabled",
    "rollback_to",
    "export_ops_since",
    "validate_op",
    "get_replay_ops",
    "get_name",
    "set_name",
];
