/**
 * sync-client.ts — ADR-0008 Phase 1: SyncClient
 *
 * Single class that owns the full sync protocol:
 *   - CRDT doc bytes (Automerge)
 *   - Storage (IDB in browser, R2 in CF worker, Memory in tests)
 *   - Server sync round-trip (HTTP in production, direct fn in tests)
 *   - Cross-tab/cross-actor messaging (BroadcastChannel in browser, direct in tests)
 *   - Network state (online/offline, unsent op queue, auto-resync on reconnect)
 *   - Structured tracing (every event logged, assertable in tests and CI)
 *
 * The WASM adapter is the REAL sync WASM in all environments.
 * Only storage and network are swapped between production and tests.
 *
 * Lives in systems/sync/ts/ — imported by truck (and any future system).
 * Has zero knowledge of CAD geometry, replay, or truck-specific state.
 */

import type { CadOperation } from './sync-types.generated';
import type { SyncWasmAdapter } from './sync-wasm-adapter.generated';
export type { SyncWasmAdapter }; // re-export for consumers (history-domain, tests)

// ── Adapter interfaces ────────────────────────────────────────────────────────

// SyncWasmAdapter imported from sync-wasm-adapter.generated.ts (generated by gen-adapters.ts)

/** Persistent storage — IDB in browser, R2 in worker, Map in tests. */
export interface SyncStorageAdapter {
  save(modelId: string, bytes: Uint8Array): Promise<void>;
  load(modelId: string): Promise<Uint8Array | null>;
  delete(modelId: string): Promise<void>;
}

/**
 * DocStore — alias for SyncStorageAdapter used by R2DocStore in the CF worker.
 * Keeping this name for backward compat with worker/src/doc-store.ts imports.
 */
export type DocStore = SyncStorageAdapter;

/**
 * Network adapter — HTTP+SSE in production, direct function call in tests.
 *
 * NOTE: The adapter owns the connection lifecycle. `postSync` sends local doc
 * bytes to the server and receives the merged doc back. `onRemoteChange`
 * registers a callback that fires whenever another actor changes the doc
 * (SSE `doc-changed` event in production, direct invocation in tests).
 */
export interface SyncNetworkAdapter {
  postSync(modelId: string, bytes: Uint8Array, actorId: string): Promise<Uint8Array | null>;
  onRemoteChange(modelId: string, callback: () => void): void;
  disconnect(): void;
}

// ── Structured tracing ────────────────────────────────────────────────────────

export type SyncEventType =
  | 'add_op'
  | 'undo_op'
  | 'redo_op'
  | 'undo_group'
  | 'redo_group'
  | 'rollback'
  | 'load_storage'
  | 'save_storage'
  | 'sync_start'
  | 'sync_complete'
  | 'sync_error'
  | 'remote_change'
  | 'merge'
  | 'network_online'
  | 'network_offline'
  | 'queue_op'
  | 'flush_queue';

export interface SyncLogEntry {
  ts: number;
  modelId: string;
  actorId: string;
  event: SyncEventType;
  detail: Record<string, unknown>;
}

/**
 * SyncMessage — BroadcastChannel wire format for cross-tab CRDT merge.
 *
 * Tab A applies an op → sends SyncMessage via BroadcastChannel.
 * Tab B receives → merges doc bytes → triggers replay.
 *
 * Owned here (sync system) not in truck — cross-tab sync is a sync concern.
 */
export interface SyncMessage {
  type: 'doc_update';
  modelId: string;   // Filter: only merge if matches local model
  bytes: number[];   // Uint8Array serialised as Array (structured clone safe)
  tabId: string;     // Filter: ignore own tab's messages
}

// ── SyncClient ────────────────────────────────────────────────────────────────

export interface SyncClientOptions {
  actorId: string;
  debounceMs?: number;       // default 2000
  maxLogEntries?: number;    // default 200
}

export class SyncClient {
  private _docBytes: Uint8Array | null = null;
  private _modelId: string | null = null;
  private _syncing = false;
  private _syncTimer: ReturnType<typeof setTimeout> | null = null;
  private _online = true;
  private _pendingSync = false;  // queued while offline

  readonly syncLog: SyncLogEntry[] = [];
  private readonly _maxLog: number;
  private readonly _debounceMs: number;

  // ── Events emitted to consumers (truck's history-domain, etc.) ────────────
  onRemoteOps?: (ops: CadOperation[]) => void;
  onSyncComplete?: (hadNewOps: boolean) => void;
  onNetworkState?: (online: boolean) => void;
  onError?: (error: Error, context: string) => void;

  constructor(
    private readonly wasm: SyncWasmAdapter,
    private readonly storage: SyncStorageAdapter,
    private readonly network: SyncNetworkAdapter,
    private readonly opts: SyncClientOptions,
  ) {
    this._debounceMs = opts.debounceMs ?? 2000;
    this._maxLog = opts.maxLogEntries ?? 200;
  }

  // ── Lifecycle ─────────────────────────────────────────────────────────────

  /**
   * Start listening for remote changes on a model.
   * Call after loadFromStorage or createDoc.
   */
  listen(modelId: string): void {
    this.network.onRemoteChange(modelId, () => {
      this._log('remote_change', { modelId });
      this._triggerRemoteSync();
    });
  }

  disconnect(): void {
    this.network.disconnect();
    if (this._syncTimer) clearTimeout(this._syncTimer);
  }

  // ── Network state ─────────────────────────────────────────────────────────

  goOffline(): void {
    this._online = false;
    this._log('network_offline', {});
    this.onNetworkState?.(false);
  }

  goOnline(): void {
    this._online = true;
    this._log('network_online', {});
    this.onNetworkState?.(true);
    // Flush any queued sync
    if (this._pendingSync && this._modelId) {
      this._log('flush_queue', { modelId: this._modelId });
      this._pendingSync = false;
      this.syncWithServer();
    }
  }

  get isOnline(): boolean { return this._online; }

  // ── Doc lifecycle ─────────────────────────────────────────────────────────

  /** Create a fresh empty doc. Does not save to storage. */
  async createDoc(modelId: string): Promise<void> {
    this._docBytes = await this.wasm.create_doc();
    this._modelId = modelId;
  }

  /** Load doc from storage. Returns true if found. */
  async loadFromStorage(modelId: string): Promise<boolean> {
    const bytes = await this.storage.load(modelId);
    if (!bytes) {
      this._log('load_storage', { modelId, found: false });
      return false;
    }
    this._docBytes = bytes;
    this._modelId = modelId;
    this._log('load_storage', { modelId, found: true });
    return true;
  }

  /** Adopt externally-provided doc bytes (e.g. from server bootstrap). */
  adoptDoc(modelId: string, bytes: Uint8Array): void {
    this._docBytes = bytes;
    this._modelId = modelId;
  }

  /** Save current doc to storage. */
  async saveToStorage(): Promise<void> {
    if (!this._docBytes || !this._modelId) return;
    await this.storage.save(this._modelId, this._docBytes);
    this._log('save_storage', { modelId: this._modelId });
  }

  // ── Op recording ──────────────────────────────────────────────────────────

  /** Record a completed op into the CRDT doc. */
  async addOp(op: CadOperation): Promise<void> {
    if (!this._docBytes || !this._modelId) return;
    this._docBytes = await this.wasm.apply_op(this._docBytes, JSON.stringify(op));
    this._log('add_op', { modelId: this._modelId, opType: op.type, opId: op.id });
    await this.saveToStorage();
    this._scheduleSyncIfOnline();
  }

  /** Disable an op by ID (undo). */
  async setOpEnabled(opId: string, enabled: boolean): Promise<void> {
    if (!this._docBytes || !this._modelId) return;
    this._docBytes = await this.wasm.set_op_enabled(this._docBytes, opId, enabled);
    this._log(enabled ? 'redo_op' : 'undo_op', { modelId: this._modelId, opId });
    await this.saveToStorage();
    this._scheduleSyncIfOnline();
  }

  /** Disable all ops in a group. */
  async setGroupEnabled(groupId: string, enabled: boolean): Promise<void> {
    if (!this._docBytes || !this._modelId) return;
    this._docBytes = await this.wasm.set_group_enabled(this._docBytes, groupId, enabled);
    this._log(enabled ? 'redo_group' : 'undo_group', { modelId: this._modelId, groupId });
    await this.saveToStorage();
    this._scheduleSyncIfOnline();
  }

  /** Disable all own ops after toIndex. */
  async rollbackTo(toIndex: number): Promise<void> {
    if (!this._docBytes || !this._modelId) return;
    this._docBytes = await this.wasm.rollback_to(this._docBytes, this.opts.actorId, toIndex);
    this._log('rollback', { modelId: this._modelId, toIndex });
    await this.saveToStorage();
    this._scheduleSyncIfOnline();
  }

  // ── Read state ────────────────────────────────────────────────────────────

  async getOps(): Promise<CadOperation[]> {
    if (!this._docBytes) return [];
    try { return JSON.parse(await this.wasm.get_ops(this._docBytes)); }
    catch { return []; }
  }

  async getReplayOps(): Promise<CadOperation[]> {
    if (!this._docBytes) return [];
    try { return JSON.parse(await this.wasm.get_replay_ops(this._docBytes)); }
    catch { return []; }
  }

  async getOpCount(): Promise<number> {
    if (!this._docBytes) return 0;
    try { return await this.wasm.get_op_count(this._docBytes); }
    catch { return 0; }
  }

  async getName(): Promise<string> {
    if (!this._docBytes) return '';
    try { return await this.wasm.get_name(this._docBytes); }
    catch { return ''; }
  }

  async setName(name: string): Promise<void> {
    if (!this._docBytes) return;
    this._docBytes = await this.wasm.set_name(this._docBytes, name);
  }

  get docBytes(): Uint8Array | null { return this._docBytes; }
  get modelId(): string | null { return this._modelId; }
  get actorId(): string { return this.opts.actorId; }

  async canUndo(): Promise<boolean> {
    return (await this.getOps()).some(op => op.actorId === this.opts.actorId && op.enabled);
  }

  async canRedo(): Promise<boolean> {
    const ops = await this.getOps();
    let foundDisabled = false;
    for (let i = ops.length - 1; i >= 0; i--) {
      if (ops[i].actorId === this.opts.actorId) {
        if (!ops[i].enabled) foundDisabled = true;
        else break;
      }
    }
    return foundDisabled;
  }

  // ── Server sync ───────────────────────────────────────────────────────────

  /** Push local doc to server, merge returned doc, return whether new ops arrived. */
  async syncWithServer(): Promise<{ hadNewOps: boolean }> {
    if (!this._docBytes || !this._modelId || this._syncing) {
      return { hadNewOps: false };
    }
    if (!this._online) {
      this._pendingSync = true;
      this._log('queue_op', { modelId: this._modelId, reason: 'offline' });
      return { hadNewOps: false };
    }

    this._syncing = true;
    this._log('sync_start', { modelId: this._modelId });

    try {
      const serverDoc = await this.network.postSync(
        this._modelId,
        this._docBytes,
        this.opts.actorId,
      );

      if (!serverDoc) {
        this._log('sync_error', { modelId: this._modelId, reason: 'no response' });
        return { hadNewOps: false };
      }

      const localOpCount = await this.getOpCount();
      this._docBytes = await this.wasm.merge_docs(this._docBytes, serverDoc);
      const mergedOpCount = await this.getOpCount();
      const hadNewOps = mergedOpCount > localOpCount;

      this._log('merge', {
        modelId: this._modelId,
        localOpCount,
        mergedOpCount,
        hadNewOps,
        source: 'server',
      });

      await this.saveToStorage();
      this.onSyncComplete?.(hadNewOps);

      if (hadNewOps) {
        const newOps = (await this.getOps()).slice(localOpCount);
        this.onRemoteOps?.(newOps);
      }

      this._log('sync_complete', { modelId: this._modelId, hadNewOps, mergedOpCount });
      return { hadNewOps };

    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      this._log('sync_error', { modelId: this._modelId, error: message });
      this.onError?.(err instanceof Error ? err : new Error(message), 'syncWithServer');
      return { hadNewOps: false };
    } finally {
      this._syncing = false;
    }
  }

  // ── Internal ──────────────────────────────────────────────────────────────

  private _scheduleSyncIfOnline(): void {
    if (!this._online) {
      this._pendingSync = true;
      return;
    }
    if (this._syncTimer) clearTimeout(this._syncTimer);
    this._syncTimer = setTimeout(() => {
      this._syncTimer = null;
      this.syncWithServer();
    }, this._debounceMs);
  }

  private _triggerRemoteSync(): void {
    // Remote change arrived — sync immediately (don't debounce)
    if (this._syncTimer) clearTimeout(this._syncTimer);
    this.syncWithServer();
  }

  private _log(event: SyncEventType, detail: Record<string, unknown>): void {
    const entry: SyncLogEntry = {
      ts: Date.now(),
      modelId: this._modelId ?? '',
      actorId: this.opts.actorId,
      event,
      detail,
    };
    this.syncLog.push(entry);
    // Trim to max
    if (this.syncLog.length > this._maxLog) {
      this.syncLog.splice(0, this.syncLog.length - this._maxLog);
    }
    // Structured console output — assertable in tests
    console.log(`[sync:${event}]`, JSON.stringify(detail));
  }
}
