// GENERATED by scripts/gen-sync-types.ts — do not edit.
// Source: systems/sync/sync-schema.json (from Rust Op struct with #[derive(JsonSchema)])
// Chain: Rust Op → sync-schema.json → gen-sync-types.ts → this file
// Re-generate: bun scripts/gen-sync-types.ts

/**
 * CadOperation — matches the Rust `Op` struct exactly.
 * Field names reflect serde renames (actorId, type, groupId).
 */
export interface CadOperation {
  actorId: string;
  enabled: boolean;
  groupId?: string | null;
  id: string;
  /** Params serialised to/from JSON string in Automerge storage */
  params: Record<string, any>;
  timestamp: number;
  /** Command name, e.g. "add_cube" (serialised as "type" to match JS) */
  type: string;
}
