
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * List all demo workers and whether they are currently running.
 * On mobile, running is always false — workers live on the server.
 */
async listWorkers() : Promise<WorkerStatus[]> {
    return await TAURI_INVOKE("list_workers");
},
/**
 * Spawn a bun demo worker by name. Desktop only.
 */
async startWorker(name: string) : Promise<Result<WorkerStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_worker", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop a running bun demo worker by name. Desktop only.
 */
async stopWorker(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_worker", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check whether a worker's TCP port is reachable. Desktop only.
 */
async pingWorker(port: number) : Promise<boolean> {
    return await TAURI_INVOKE("ping_worker", { port });
},
/**
 * Scrub a JSON log entry using the native plat-observe crate (no WASM).
 */
async nativeScrub(json: string) : Promise<ScrubResult> {
    return await TAURI_INVOKE("native_scrub", { json });
},
/**
 * Run a sampling decision using the native plat-observe crate.
 */
async nativeSample(rate: number, seed: number) : Promise<SampleResult> {
    return await TAURI_INVOKE("native_sample", { rate, seed });
},
/**
 * Return the plat-observe crate version running natively.
 */
async nativeVersion() : Promise<string> {
    return await TAURI_INVOKE("native_version");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type SampleResult = { keep: boolean; rate: number; seed: number }
export type ScrubResult = { original: string; scrubbed: string; changed: boolean }
export type WorkerStatus = { name: string; port: number; running: boolean; url: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
