// api-contract.ts — Compile-time contract for all browser API calls.
//
// This file exercises every api.* call pattern used by the browser .js files.
// It produces NO runtime output — it exists only for `tsc --noEmit`.
//
// If a route changes in index.ts, this file fails to compile, telling you
// exactly which browser JS files need updating.
//
// To check:  bun run typecheck
// Watcher:   watchexec runs it on every .ts change in web/src/ and worker/src/

import { api } from './api-client';

// Fake values — never executed, only type-checked
declare const modelId: string;
declare const id: string;
declare const name: string;
declare const scene: string;
declare const state: Record<string, unknown>;
declare const result: { error?: string };

// NOTE: worker-relay.js and state.js use api.cad[...] routes which are
// dynamically generated by mountModule() — they're type-opaque and not
// part of the hc contract. Those calls use the typed client at runtime
// but can't be checked at compile time. If a cad route changes, tests
// and the SSE relay will catch it.

// ── ui.js ────────────────────────────────────────────────────────
// Line 70: save model to cloud
void api.models[':id'].$put({
  param: { id },
  json: { name, scene },
});

// ── cad-gallery.js ───────────────────────────────────────────────
// Line 35: list models
void api.models.$get();

// Line 48: delete model
void api.models[':id'].$delete({ param: { id } });

// ── Response types — verify .json() returns the right shape ──────
async function _checkResponseTypes() {
  const listRes = await api.models.$get();
  const _models: { id: string; name: string; objectCount: number }[] = await listRes.json() as any;

  const getRes = await api.models[':id'].$get({ param: { id } });
  const _manifest: { id: string; name: string; hasThumbnail: boolean } = await getRes.json() as any;

  const putRes = await api.models[':id'].$put({ param: { id }, json: { name, scene } });
  const _saved: { id: string; name: string; objectCount: number } = await putRes.json() as any;
}
