#!/usr/bin/env bun
/**
 * gen-adapters.ts — ADR-0004 Phase 0: Generate per-target adapter code from cad-schema.json.
 *
 * Reads the `boundaries` section of cad-schema.json and emits:
 *   1. CF Worker WASM loaders  (replaces hand-written truck-wasm.ts / sync-wasm.ts)
 *   2. Browser command routing  (typed command→domain map for BrowserModuleRouter)
 *
 * Usage:
 *   bun scripts/gen-adapters.ts            (generate all adapters)
 *   bun scripts/gen-adapters.ts --check    (verify generated files are up-to-date)
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { createHash } from 'crypto';

const SCHEMA_PATH = 'systems/truck/cad-schema.json';
const schema = JSON.parse(readFileSync(SCHEMA_PATH, 'utf-8'));

const boundaries = schema.boundaries;
if (!boundaries?.modules) {
  console.error('ERROR: cad-schema.json has no boundaries.modules — run `bun run build:truck` first');
  process.exit(1);
}

const schemaHash = createHash('sha256')
  .update(JSON.stringify(boundaries))
  .digest('hex')
  .slice(0, 12);

const HEADER = (target: string) =>
  `// Generated by gen-adapters.ts (ADR-0004 Phase 0) — do not edit.\n// Source: cad-schema.json boundaries [${schemaHash}]\n// Target: ${target}\n`;

// ─── CF Worker: truck-geometry loader ────────────────────────────

function genCfTruckWasm(): string {
  const exports = boundaries.modules['truck-geometry']?.exports as string[];
  if (!exports) throw new Error('No truck-geometry module in boundaries');

  return `${HEADER('cf-worker / truck-geometry')}
/**
 * Headless truck-webgpu-gui WASM loader for Cloudflare Workers.
 *
 * Lazy-init pattern: import the module, instantiate with glue imports on first use.
 * Generated from cad-schema.json boundaries — ${exports.length} commands.
 */

// Wrangler imports .wasm files as WebAssembly.Module
import wasmModule from '../pkg/truck_webgpu_gui_bg.wasm';
// @ts-expect-error — no .d.ts for the bg.js glue (generated code)
import * as bg from '../pkg/truck_webgpu_gui_bg.js';

let initialized = false;

export async function initHeadlessWasm(): Promise<typeof bg> {
  if (initialized) return bg;

  // Collect all glue functions the WASM module needs.
  // WebAssembly.instantiate ignores extras, so we can pass all bg exports.
  const glueImports: WebAssembly.ModuleImports = {};
  for (const [key, value] of Object.entries(bg)) {
    if (typeof value === 'function') {
      glueImports[key] = value as WebAssembly.ImportValue;
    }
  }

  const imports: WebAssembly.Imports = {
    './truck_webgpu_gui_bg.js': glueImports,
  };

  const instance = await WebAssembly.instantiate(wasmModule, imports);
  bg.__wbg_set_wasm(instance.exports);
  (instance.exports as unknown as { __wbindgen_start: () => void }).__wbindgen_start();
  initialized = true;
  return bg;
}

// Re-export the HeadlessController type
export type { HeadlessController } from '../pkg/truck_webgpu_gui.js';
`;
}

// ─── CF Worker: truck-sync loader ────────────────────────────────

function genCfSyncWasm(): string {
  const exports = boundaries.modules['truck-sync']?.exports as string[];
  if (!exports) throw new Error('No truck-sync module in boundaries');

  // Map of WASM export → wrapper function config
  // Each entry: [wrapperName, params, paramTypes, returnType]
  const syncWrappers: Array<{
    wasmFn: string;
    wrapperName: string;
    params: string;
    call: string;
    returnType: string;
  }> = [
    { wasmFn: 'create_doc', wrapperName: 'syncCreate', params: '', call: 'bg.create_doc()', returnType: 'Uint8Array<ArrayBuffer>' },
    { wasmFn: 'apply_op', wrapperName: 'syncApplyOp', params: 'doc: Uint8Array, opJson: string', call: 'bg.apply_op(doc, opJson)', returnType: 'Uint8Array<ArrayBuffer>' },
    { wasmFn: 'merge_docs', wrapperName: 'syncMergeDocs', params: 'local: Uint8Array, remote: Uint8Array', call: 'bg.merge_docs(local, remote)', returnType: 'Uint8Array<ArrayBuffer>' },
    { wasmFn: 'get_ops', wrapperName: 'syncGetOps', params: 'doc: Uint8Array', call: 'bg.get_ops(doc)', returnType: 'string' },
    { wasmFn: 'set_op_enabled', wrapperName: 'syncSetOpEnabled', params: 'doc: Uint8Array, opId: string, enabled: boolean', call: 'bg.set_op_enabled(doc, opId, enabled)', returnType: 'Uint8Array<ArrayBuffer>' },
    { wasmFn: 'set_group_enabled', wrapperName: 'syncSetGroupEnabled', params: 'doc: Uint8Array, groupId: string, enabled: boolean', call: 'bg.set_group_enabled(doc, groupId, enabled)', returnType: 'Uint8Array<ArrayBuffer>' },
    { wasmFn: 'rollback_to', wrapperName: 'syncRollbackTo', params: 'doc: Uint8Array, actorId: string, toIndex: number', call: 'bg.rollback_to(doc, actorId, toIndex)', returnType: 'Uint8Array<ArrayBuffer>' },
    { wasmFn: 'export_ops_since', wrapperName: 'syncExportOpsSince', params: 'doc: Uint8Array, sinceIndex: number', call: 'bg.export_ops_since(doc, sinceIndex)', returnType: 'string' },
    { wasmFn: 'validate_op', wrapperName: 'syncValidateOp', params: 'opJson: string', call: 'bg.validate_op(opJson)', returnType: 'boolean' },
    { wasmFn: 'get_replay_ops', wrapperName: 'syncGetReplayOps', params: 'doc: Uint8Array', call: 'bg.get_replay_ops(doc)', returnType: 'string' },
  ];

  // Only generate wrappers for exports that are in the schema
  const activeWrappers = syncWrappers.filter(w => exports.includes(w.wasmFn));

  const wrapperCode = activeWrappers.map(w => {
    const doc = w.wasmFn === 'get_replay_ops'
      ? '\n/** Returns enabled ops in index order — the geometry layer executes each in sequence. */'
      : '';
    return `${doc}
export async function ${w.wrapperName}(${w.params}): Promise<${w.returnType}> {
  await initSyncWasm();
  return ${w.call} as ${w.returnType};
}`;
  }).join('\n');

  return `${HEADER('cf-worker / truck-sync')}
/**
 * truck-sync WASM loader for Cloudflare Workers.
 *
 * Lazy-init pattern matching truck-wasm loader.
 * Generated from cad-schema.json boundaries — ${exports.length} exports.
 */

// Wrangler imports .wasm files as WebAssembly.Module
import wasmModule from '../pkg-sync/truck_sync_bg.wasm';
// @ts-expect-error — generated glue, no .d.ts for bg.js
import * as bg from '../pkg-sync/truck_sync_bg.js';

let initialized = false;

async function initSyncWasm(): Promise<void> {
  if (initialized) return;

  const glueImports: WebAssembly.ModuleImports = {};
  for (const [key, value] of Object.entries(bg)) {
    if (typeof value === 'function') {
      glueImports[key] = value as WebAssembly.ImportValue;
    }
  }

  const instance = await WebAssembly.instantiate(wasmModule, {
    './truck_sync_bg.js': glueImports,
  });
  bg.__wbg_set_wasm(instance.exports);
  initialized = true;
}
${wrapperCode}
`;
}

// ─── Browser: command routing map ────────────────────────────────

function genBrowserDispatch(): string {
  const commands = schema.commands as Record<string, { domain: string }>;
  const entries = Object.entries(commands)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, cmd]) => `  '${name}': '${cmd.domain}',`)
    .join('\n');

  const domains = [...new Set(Object.values(commands).map((c: any) => c.domain))].sort();

  return `${HEADER('browser')}
/**
 * Command → domain routing map.
 *
 * Used by BrowserModuleRouter to route commands to the correct WASM module
 * when multiple modules are registered (Phase 1+).
 *
 * Domains: ${domains.join(', ')}
 * Commands: ${Object.keys(commands).length}
 */

export type CadDomain = ${domains.map(d => `'${d}'`).join(' | ')};

export const commandDomain: Record<string, CadDomain> = {
${entries}
};

/** All command names known to the schema. */
export type CadCommandName = keyof typeof commandDomain;

/** All WASM modules declared in boundaries. */
export const wasmModules = ${JSON.stringify(Object.keys(boundaries.modules))} as const;
export type WasmModuleName = typeof wasmModules[number];
`;
}

// ─── Output ──────────────────────────────────────────────────────

interface GeneratedFile {
  path: string;
  content: string;
}

const outputs: GeneratedFile[] = [
  { path: 'systems/truck/worker/src/truck-wasm.generated.ts', content: genCfTruckWasm() },
  { path: 'systems/truck/worker/src/sync-wasm.generated.ts', content: genCfSyncWasm() },
  { path: 'systems/truck/web/cad-dispatch.generated.ts', content: genBrowserDispatch() },
];

const checkMode = process.argv.includes('--check');

let allFresh = true;
for (const { path, content } of outputs) {
  if (checkMode) {
    if (!existsSync(path)) {
      console.error(`MISSING: ${path}`);
      allFresh = false;
      continue;
    }
    const existing = readFileSync(path, 'utf-8');
    if (existing !== content) {
      console.error(`STALE: ${path} — run \`bun run gen:adapters\` to regenerate`);
      allFresh = false;
    } else {
      console.log(`OK: ${path}`);
    }
  } else {
    writeFileSync(path, content);
    console.log(`wrote ${path}`);
  }
}

if (checkMode && !allFresh) {
  process.exit(1);
}
