#!/usr/bin/env bun
/**
 * gen-adapters.ts — ADR-0004 Phase 0: Generate per-target adapter code from cad-schema.json.
 *
 * Reads the `boundaries` section of cad-schema.json and emits:
 *   1. CF Worker WASM loaders  (replaces hand-written truck-wasm.ts / sync-wasm.ts)
 *   2. Browser command routing  (typed command→domain map for BrowserModuleRouter)
 *
 * Usage:
 *   bun scripts/gen-adapters.ts            (generate all adapters)
 *   bun scripts/gen-adapters.ts --check    (verify generated files are up-to-date)
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { createHash } from 'crypto';

const SCHEMA_PATH = 'systems/truck/cad-schema.json';
const schema = JSON.parse(readFileSync(SCHEMA_PATH, 'utf-8'));

const boundaries = schema.boundaries;
if (!boundaries?.modules) {
  console.error('ERROR: cad-schema.json has no boundaries.modules — run `bun run build:truck` first');
  process.exit(1);
}

const schemaHash = createHash('sha256')
  .update(JSON.stringify(boundaries))
  .digest('hex')
  .slice(0, 12);

const HEADER = (target: string) =>
  `// Generated by gen-adapters.ts (ADR-0004 Phase 0) — do not edit.\n// Source: cad-schema.json boundaries [${schemaHash}]\n// Target: ${target}\n`;

// ─── CF Worker: truck-geometry loader ────────────────────────────

function genCfTruckWasm(): string {
  const exports = boundaries.modules['truck-geometry']?.exports as string[];
  if (!exports) throw new Error('No truck-geometry module in boundaries');

  return `${HEADER('cf-worker / truck-geometry')}
/**
 * Headless truck-cad WASM loader for Cloudflare Workers.
 *
 * Lazy-init pattern: import the module, instantiate with glue imports on first use.
 * Generated from cad-schema.json boundaries — ${exports.length} commands.
 */

// Wrangler: default import is WebAssembly.Module.
// vitest (vite-plugin-wasm): default is undefined, namespace has instantiated exports.
import wasmDefault from '../pkg/truck_cad_bg.wasm';
import * as wasmStar from '../pkg/truck_cad_bg.wasm';
// @ts-expect-error — no .d.ts for the bg.js glue (generated code)
import * as bg from '../pkg/truck_cad_bg.js';

let initialized = false;

export async function initHeadlessWasm(): Promise<typeof bg> {
  if (initialized) return bg;

  if (wasmDefault instanceof WebAssembly.Module) {
    // Wrangler: instantiate from Module with bg glue as imports
    const glueImports: WebAssembly.ModuleImports = {};
    for (const [key, value] of Object.entries(bg)) {
      if (typeof value === 'function') {
        glueImports[key] = value as WebAssembly.ImportValue;
      }
    }
    const instance = await WebAssembly.instantiate(wasmDefault, {
      './truck_cad_bg.js': glueImports,
    });
    bg.__wbg_set_wasm(instance.exports);
    (instance.exports as unknown as { __wbindgen_start: () => void }).__wbindgen_start();
  } else {
    // vitest (vite-plugin-wasm): namespace has already-instantiated exports
    bg.__wbg_set_wasm(wasmStar as unknown as WebAssembly.Exports);
  }
  initialized = true;
  return bg;
}

// Re-export the HeadlessController type
export type { HeadlessController } from '../pkg/truck_cad.js';
`;
}

// ─── Sync WASM wrapper definitions (shared by loader + adapter generator) ────
// clientAdapter: true  → included in SyncWasmAdapter (used by SyncClient)
// clientAdapter: false → server/worker-only, not in SyncWasmAdapter
const syncWrappers: Array<{
  wasmFn: string;
  wrapperName: string;
  params: string;
  call: string;
  returnType: string;
  clientAdapter: boolean;
}> = [
  { wasmFn: 'create_doc',          wrapperName: 'syncCreate',            params: '',                                                  call: 'bg.create_doc()',                       returnType: 'Uint8Array<ArrayBuffer>', clientAdapter: true  },
  { wasmFn: 'apply_op',            wrapperName: 'syncApplyOp',           params: 'doc: Uint8Array, opJson: string',                    call: 'bg.apply_op(doc, opJson)',              returnType: 'Uint8Array<ArrayBuffer>', clientAdapter: true  },
  { wasmFn: 'merge_docs',          wrapperName: 'syncMergeDocs',         params: 'local: Uint8Array, remote: Uint8Array',              call: 'bg.merge_docs(local, remote)',          returnType: 'Uint8Array<ArrayBuffer>', clientAdapter: true  },
  { wasmFn: 'merge_docs_with_info',wrapperName: 'syncMergeDocsWithInfo', params: 'local: Uint8Array, remote: Uint8Array',              call: 'bg.merge_docs_with_info(local, remote)',returnType: 'SyncMergeResult',        clientAdapter: false },
  { wasmFn: 'get_ops',             wrapperName: 'syncGetOps',            params: 'doc: Uint8Array',                                   call: 'bg.get_ops(doc)',                       returnType: 'string',                 clientAdapter: true  },
  { wasmFn: 'get_op_count',        wrapperName: 'syncGetOpCount',        params: 'doc: Uint8Array',                                   call: 'bg.get_op_count(doc)',                  returnType: 'number',                 clientAdapter: true  },
  { wasmFn: 'set_op_enabled',      wrapperName: 'syncSetOpEnabled',      params: 'doc: Uint8Array, opId: string, enabled: boolean',    call: 'bg.set_op_enabled(doc, opId, enabled)', returnType: 'Uint8Array<ArrayBuffer>', clientAdapter: true  },
  { wasmFn: 'set_group_enabled',   wrapperName: 'syncSetGroupEnabled',   params: 'doc: Uint8Array, groupId: string, enabled: boolean', call: 'bg.set_group_enabled(doc, groupId, enabled)', returnType: 'Uint8Array<ArrayBuffer>', clientAdapter: true },
  { wasmFn: 'rollback_to',         wrapperName: 'syncRollbackTo',        params: 'doc: Uint8Array, actorId: string, toIndex: number',  call: 'bg.rollback_to(doc, actorId, toIndex)', returnType: 'Uint8Array<ArrayBuffer>', clientAdapter: true  },
  { wasmFn: 'export_ops_since',    wrapperName: 'syncExportOpsSince',    params: 'doc: Uint8Array, sinceIndex: number',                call: 'bg.export_ops_since(doc, sinceIndex)',  returnType: 'string',                 clientAdapter: false },
  { wasmFn: 'validate_op',         wrapperName: 'syncValidateOp',        params: 'opJson: string',                                    call: 'bg.validate_op(opJson)',                returnType: 'boolean',                clientAdapter: false },
  { wasmFn: 'get_replay_ops',      wrapperName: 'syncGetReplayOps',      params: 'doc: Uint8Array',                                   call: 'bg.get_replay_ops(doc)',                returnType: 'string',                 clientAdapter: true  },
  { wasmFn: 'get_name',            wrapperName: 'syncGetName',           params: 'doc: Uint8Array',                                   call: 'bg.get_name(doc)',                      returnType: 'string',                 clientAdapter: true  },
  { wasmFn: 'set_name',            wrapperName: 'syncSetName',           params: 'doc: Uint8Array, name: string',                     call: 'bg.set_name(doc, name)',                returnType: 'Uint8Array<ArrayBuffer>', clientAdapter: true  },
];

// ─── CF Worker: truck-sync loader ────────────────────────────────

function genCfSyncWasm(): string {
  const exports = boundaries.modules['truck-sync']?.exports as string[];
  if (!exports) throw new Error('No truck-sync module in boundaries');

  // syncWrappers defined at module scope — used here + in adapter generators
  // Only generate wrappers for exports that are in the schema
  const activeWrappers = syncWrappers.filter(w => exports.includes(w.wasmFn));

  const wrapperCode = activeWrappers.map(w => {
    const doc = w.wasmFn === 'get_replay_ops'
      ? '\n/** Returns enabled ops in index order — the geometry layer executes each in sequence. */'
      : '';
    return `${doc}
export async function ${w.wrapperName}(${w.params}): Promise<${w.returnType}> {
  await initSyncWasm();
  return ${w.call} as ${w.returnType};
}`;
  }).join('\n');

  return `${HEADER('cf-worker / truck-sync')}
/**
 * truck-sync WASM loader for Cloudflare Workers.
 *
 * Lazy-init pattern matching truck-wasm loader.
 * Generated from cad-schema.json boundaries — ${exports.length} exports.
 */

// Wrangler: default import is WebAssembly.Module.
// vitest (vite-plugin-wasm): default is undefined, namespace has instantiated exports.
import wasmDefault from '../pkg-sync/truck_sync_bg.wasm';
import * as wasmStar from '../pkg-sync/truck_sync_bg.wasm';
// @ts-expect-error — generated glue, no .d.ts for bg.js
import * as bg from '../pkg-sync/truck_sync_bg.js';

let initialized = false;

async function initSyncWasm(): Promise<void> {
  if (initialized) return;

  if (wasmDefault instanceof WebAssembly.Module) {
    // Wrangler: instantiate from Module with bg glue as imports
    const glueImports: WebAssembly.ModuleImports = {};
    for (const [key, value] of Object.entries(bg)) {
      if (typeof value === 'function') {
        glueImports[key] = value as WebAssembly.ImportValue;
      }
    }
    const instance = await WebAssembly.instantiate(wasmDefault, {
      './truck_sync_bg.js': glueImports,
    });
    bg.__wbg_set_wasm(instance.exports);
  } else {
    // vitest (vite-plugin-wasm): namespace has already-instantiated exports
    bg.__wbg_set_wasm(wasmStar as unknown as WebAssembly.Exports);
  }
  initialized = true;
}

/** Result of merge_docs_with_info — tells callers if the merge introduced new ops. */
export interface SyncMergeResult {
  doc: Uint8Array<ArrayBuffer>;
  localOpCount: number;
  mergedOpCount: number;
  hadNewOps: boolean;
}
${wrapperCode}
`;
}

// ─── Browser: command routing map ────────────────────────────────

function genBrowserDispatch(): string {
  const commands = schema.commands as Record<string, { domain: string }>;
  const entries = Object.entries(commands)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, cmd]) => `  '${name}': '${cmd.domain}',`)
    .join('\n');

  const domains = [...new Set(Object.values(commands).map((c: any) => c.domain))].sort();

  return `${HEADER('browser')}
/**
 * Command → domain routing map.
 *
 * Used by BrowserModuleRouter to route commands to the correct WASM module
 * when multiple modules are registered (Phase 1+).
 *
 * Domains: ${domains.join(', ')}
 * Commands: ${Object.keys(commands).length}
 */

export type CadDomain = ${domains.map(d => `'${d}'`).join(' | ')};

export const commandDomain: Record<string, CadDomain> = {
${entries}
};

/** All command names known to the schema. */
export type CadCommandName = keyof typeof commandDomain;

/** All WASM modules declared in boundaries. */
export const wasmModules = ${JSON.stringify(Object.keys(boundaries.modules))} as const;
export type WasmModuleName = typeof wasmModules[number];
`;
}

// ─── Native Rust: command list + domain routing ──────────────────

function genNativeCommands(): string {
  const commands = schema.commands as Record<string, { domain: string; readonly: boolean; ephemeral: boolean }>;
  const sorted = Object.entries(commands).sort(([a], [b]) => a.localeCompare(b));
  const domains = [...new Set(sorted.map(([, c]) => c.domain))].sort();

  const domainArms = domains.map(domain => {
    const cmds = sorted.filter(([, c]) => c.domain === domain);
    const names = cmds.map(([name]) => `"${name}"`).join(' | ');
    return `        ${names} => Some(CadDomain::${capitalize(domain)}),`;
  }).join('\n');

  const allNames = sorted.map(([name]) => `    "${name}",`).join('\n');

  const syncExports = (boundaries.modules['truck-sync']?.exports as string[]) || [];
  const syncNames = syncExports.map(name => `    "${name}",`).join('\n');

  return `${HEADER('native').replace(/^\/\//gm, '//')}
//! Generated command metadata for native Rust targets (ADR-0004).
//!
//! Provides: command names, domain routing, sync module exports.
//! Use via \`include!("commands_generated.rs")\` or as a standalone module.

/// All ${sorted.length} command names from cad-schema.json.
pub const COMMAND_NAMES: &[&str] = &[
${allNames}
];

/// Command domain categories.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CadDomain {
${domains.map(d => `    ${capitalize(d)},`).join('\n')}
}

/// Look up the domain for a command name.
pub fn command_domain(cmd: &str) -> Option<CadDomain> {
    match cmd {
${domainArms}
        _ => None,
    }
}

/// All ${syncExports.length} exports from the truck-sync WASM module.
pub const SYNC_EXPORTS: &[&str] = &[
${syncNames}
];
`;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// ─── Sync: SyncWasmAdapter interface ─────────────────────────────
// Generated from syncWrappers entries with clientAdapter:true.
// Imported by sync-client.ts — single source of truth for the adapter shape.

function genSyncWasmAdapter(): string {
  const exports = boundaries.modules['truck-sync']?.exports as string[];
  if (!exports) throw new Error('No truck-sync module in boundaries');

  // Only clientAdapter:true entries, filtered to what the schema exports
  const adapterWrappers = syncWrappers.filter(w => w.clientAdapter && exports.includes(w.wasmFn));

  // Map returnType to the correct Promise return
  function adapterReturn(returnType: string): string {
    if (returnType === 'Uint8Array<ArrayBuffer>') return 'Promise<Uint8Array>';
    if (returnType === 'string') return 'Promise<string>';
    if (returnType === 'number') return 'Promise<number>';
    if (returnType === 'boolean') return 'Promise<boolean>';
    return `Promise<${returnType}>`;
  }

  const methods = adapterWrappers.map(w => {
    const ret = adapterReturn(w.returnType);
    return `  ${w.wasmFn}(${w.params}): ${ret};`;
  }).join('\n');

  return `${HEADER('sync-client (SyncWasmAdapter interface)')}
/**
 * SyncWasmAdapter — interface for the truck-sync WASM module.
 *
 * Implemented by:
 *   - Real WASM: wrap the generated async functions from sync-wasm.generated.ts
 *   - Tests: wrap the same generated functions directly (no mock)
 *
 * All methods are async — matches wasm-bindgen generated signatures.
 * Generated from cad-schema.json boundaries.modules['truck-sync'] (clientAdapter:true entries).
 * ${adapterWrappers.length} methods.
 */
export interface SyncWasmAdapter {
${methods}
}
`;
}

// ─── Browser: SyncWasmAdapter implementation ─────────────────────
// Wraps the browser WASM functions (from pkg-sync/truck_sync.js) as the
// SyncWasmAdapter used by SyncClient in history-domain.ts.
// browser sync WASM functions are sync after init — wrap in Promise.resolve().

function genBrowserSyncAdapter(): string {
  const exports = boundaries.modules['truck-sync']?.exports as string[];
  if (!exports) throw new Error('No truck-sync module in boundaries');

  // All clientAdapter:true entries — SyncClient calls merge_docs after network.postSync() returns server bytes
  const adapterWrappers = syncWrappers.filter(w => w.clientAdapter && exports.includes(w.wasmFn));

  // Map wasm function params to the implementation call
  const methods = adapterWrappers.map(w => {
    const paramNames = w.params
      .split(',')
      .map(p => p.trim().split(':')[0].trim())
      .filter(Boolean)
      .join(', ');
    const call = paramNames ? `${w.wasmFn}(${paramNames})` : `${w.wasmFn}()`;
    // get_replay_ops needs special handling — not re-exported, derive from get_ops
    if (w.wasmFn === 'get_replay_ops') {
      return `    ${w.wasmFn}: (doc) => {
        const all: CadOperation[] = JSON.parse(get_ops(doc));
        return Promise.resolve(JSON.stringify(all.filter(o => o.enabled)));
    },`;
    }
    return `    ${w.wasmFn}: (${w.params ? w.params : ''}) => Promise.resolve(${call}),`;
  }).join('\n');

  const importedFns = adapterWrappers
    .filter(w => w.wasmFn !== 'get_replay_ops')
    .map(w => w.wasmFn)
    .join(', ');

  return `${HEADER('browser / sync-wasm-adapter')}
// Browser SyncWasmAdapter — wraps the sync WASM functions from pkg-sync.
// merge_docs IS included — SyncClient calls it after network.postSync() returns
// the merged server bytes. It is a local merge, not a network call.
//
// get_replay_ops is derived from get_ops + filter(enabled) because
// get_replay_ops is not re-exported from the browser WASM generated bindings.

import { ${importedFns} } from './pkg-sync/truck_sync.js';
import type { SyncWasmAdapter } from '../../sync/ts/sync-wasm-adapter.generated';
import type { CadOperation } from '../../sync/ts/sync-types.generated';

/** Real browser SyncWasmAdapter — use in CadDocumentManagerBase constructor. */
export const browserSyncWasmAdapter: SyncWasmAdapter = {
${methods}
};
`;
}

// ─── Test: SyncWasmAdapter implementation ────────────────────────
// Wraps the generated async test WASM functions for use in sync-client.test.ts.

function genTestSyncAdapter(): string {
  const exports = boundaries.modules['truck-sync']?.exports as string[];
  if (!exports) throw new Error('No truck-sync module in boundaries');

  const adapterWrappers = syncWrappers.filter(w => w.clientAdapter && exports.includes(w.wasmFn));

  const importedFns = adapterWrappers
    .filter(w => w.wasmFn !== 'get_replay_ops')
    .map(w => w.wrapperName)
    .join(', ');
  // syncMergeDocs also needed in makeServer() test helper — included via importedFns

  const methods = adapterWrappers.map(w => {
    if (w.wasmFn === 'get_replay_ops') {
      return `    ${w.wasmFn}: (doc) => syncGetReplayOps(doc),`;
    }
    const paramNames = w.params
      .split(',')
      .map(p => p.trim().split(':')[0].trim())
      .filter(Boolean);
    const call = paramNames.length ? `${w.wrapperName}(${paramNames.join(', ')})` : `${w.wrapperName}()`;
    return `    ${w.wasmFn}: (${w.params}) => ${call},`;
  }).join('\n');

  return `${HEADER('sync-test / SyncWasmAdapter implementation')}
// Test SyncWasmAdapter — wraps the generated async WASM functions.
// Identical shape to browser adapter but uses the test context WASM loader.
// Generated from cad-schema.json boundaries.modules['truck-sync'] (clientAdapter:true, no merge_docs).

import { ${importedFns}, syncGetReplayOps } from './sync-wasm.generated';
import type { SyncWasmAdapter } from '../../ts/sync-wasm-adapter.generated';

/** SyncWasmAdapter implementation using the real sync WASM — no mocks. */
export const testSyncWasmAdapter: SyncWasmAdapter = {
${methods}
};
`;
}

// ─── Output ──────────────────────────────────────────────────────

interface GeneratedFile {
  path: string;
  content: string;
}

const outputs: GeneratedFile[] = [
  { path: 'systems/sync/ts/sync-wasm-adapter.generated.ts', content: genSyncWasmAdapter() },
  { path: 'systems/truck/web/sync-wasm-adapter.generated.ts', content: genBrowserSyncAdapter() },
  { path: 'systems/sync/test/src/sync-wasm-adapter.generated.ts', content: genTestSyncAdapter() },
  { path: 'systems/truck/worker/src/truck-wasm.generated.ts', content: genCfTruckWasm() },
  { path: 'systems/truck/worker/src/sync-wasm.generated.ts', content: genCfSyncWasm() },
  { path: 'systems/sync/test/src/sync-wasm.generated.ts', content: genCfSyncWasm() },
  { path: 'systems/truck/web/cad-dispatch.generated.ts', content: genBrowserDispatch() },
  { path: 'systems/truck/crate/src/commands_generated.rs', content: genNativeCommands() },
];

const checkMode = process.argv.includes('--check');

let allFresh = true;
for (const { path, content } of outputs) {
  if (checkMode) {
    if (!existsSync(path)) {
      console.error(`MISSING: ${path}`);
      allFresh = false;
      continue;
    }
    const existing = readFileSync(path, 'utf-8');
    if (existing !== content) {
      console.error(`STALE: ${path} — run \`bun run gen:adapters\` to regenerate`);
      allFresh = false;
    } else {
      console.log(`OK: ${path}`);
    }
  } else {
    writeFileSync(path, content);
    console.log(`wrote ${path}`);
  }
}

if (checkMode && !allFresh) {
  process.exit(1);
}
