#!/usr/bin/env bun
/**
 * gen-sync-types.ts — Generate Operation TypeScript type from sync-schema.json.
 *
 * Chain: Rust Op struct (#[derive(JsonSchema)]) → sync-schema.json → this script → sync-types.generated.ts
 *
 * Usage:
 *   bun scripts/gen-sync-types.ts            (generate)
 *   bun scripts/gen-sync-types.ts --check    (verify not stale)
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';

const SCHEMA_PATH = 'systems/sync/sync-schema.json';
const OUTPUT_PATH = 'systems/sync/ts/shared/types.ts';

if (!existsSync(SCHEMA_PATH)) {
  console.error(`ERROR: ${SCHEMA_PATH} not found — run 'bun run build:sync' first`);
  process.exit(1);
}

const schema = JSON.parse(readFileSync(SCHEMA_PATH, 'utf-8'));

// Map JSON Schema types to TypeScript types
function jsonSchemaTypeToTs(prop: any): string {
  if (Array.isArray(prop.type)) {
    // e.g. ["string", "null"] → string | null
    return prop.type.map((t: string) => (t === 'null' ? 'null' : t === 'integer' ? 'number' : t)).join(' | ');
  }
  if (prop.type === 'integer') return 'number';
  if (prop.type === 'string') return 'string';
  if (prop.type === 'boolean') return 'boolean';
  if (prop.type === 'number') return 'number';
  // No type specified (e.g. params: any JSON value)
  return 'Record<string, any>';
}

const required = new Set(schema.required || []);
const props = schema.properties || {};

const fields = Object.entries(props)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([name, prop]: [string, any]) => {
    const tsType = jsonSchemaTypeToTs(prop);
    const opt = required.has(name) ? '' : '?';
    const desc = prop.description ? `  /** ${prop.description} */\n` : '';
    return `${desc}  ${name}${opt}: ${tsType};`;
  })
  .join('\n');

const content = `// GENERATED by scripts/gen-sync-types.ts — do not edit.
// Source: ${SCHEMA_PATH} (from Rust Op struct with #[derive(JsonSchema)])
// Chain: Rust Op → sync-schema.json → gen-sync-types.ts → this file
// Re-generate: bun scripts/gen-sync-types.ts

/**
 * Operation — matches the Rust \`Op\` struct exactly.
 * Field names reflect serde renames (actorId, type, groupId).
 */
export interface Operation {
${fields}
}

/** @deprecated Use Operation instead */
export type CadOperation = Operation;
`;

const checkMode = process.argv.includes('--check');

if (checkMode) {
  if (!existsSync(OUTPUT_PATH)) {
    console.error(`MISSING: ${OUTPUT_PATH}`);
    process.exit(1);
  }
  const existing = readFileSync(OUTPUT_PATH, 'utf-8');
  if (existing !== content) {
    console.error(`STALE: ${OUTPUT_PATH} — run 'bun scripts/gen-sync-types.ts' to regenerate`);
    process.exit(1);
  }
  console.log(`OK: ${OUTPUT_PATH}`);
} else {
  writeFileSync(OUTPUT_PATH, content);
  console.log(`wrote ${OUTPUT_PATH}`);
}

