// Generated by gen-adapters.ts (ADR-0004 Phase 0) — do not edit.
// Source: cad-schema.json boundaries [c3805315f942]
// Target: browser

/**
 * Command → domain routing map.
 *
 * Used by BrowserModuleRouter to route commands to the correct WASM module
 * when multiple modules are registered (Phase 1+).
 *
 * Domains: booleans, geometry, scene, sketch, style
 * Commands: 42
 */

export type CadDomain = 'booleans' | 'geometry' | 'scene' | 'sketch' | 'style';

export const commandDomain: Record<string, CadDomain> = {
  'add_cube': 'geometry',
  'add_cylinder': 'geometry',
  'add_sphere': 'geometry',
  'add_torus': 'geometry',
  'begin_sketch': 'sketch',
  'boolean_intersect': 'booleans',
  'boolean_subtract': 'booleans',
  'boolean_union': 'booleans',
  'clash_detect': 'booleans',
  'clear': 'scene',
  'delete': 'scene',
  'deselect': 'scene',
  'duplicate': 'geometry',
  'export_obj': 'scene',
  'export_scene': 'scene',
  'export_step': 'scene',
  'export_stl': 'scene',
  'get_bim_metadata': 'style',
  'get_object_style': 'style',
  'get_state': 'style',
  'import_ifc': 'scene',
  'import_scene': 'scene',
  'import_step': 'scene',
  'pick_at': 'scene',
  'pick_mesh_stats': 'style',
  'quick_rect_extrude': 'sketch',
  'rename': 'style',
  'rotate': 'geometry',
  'scale': 'geometry',
  'select': 'scene',
  'select_at': 'scene',
  'set_camera': 'style',
  'set_color': 'style',
  'set_style': 'style',
  'sketch_add_constraint': 'sketch',
  'sketch_add_edge': 'sketch',
  'sketch_add_point': 'sketch',
  'sketch_cancel': 'sketch',
  'sketch_export': 'sketch',
  'sketch_extrude': 'sketch',
  'sketch_solve': 'sketch',
  'translate': 'geometry',
};

/** All command names known to the schema. */
export type CadCommandName = keyof typeof commandDomain;

/** All WASM modules declared in boundaries. */
export const wasmModules = ["truck-geometry","truck-sync"] as const;
export type WasmModuleName = typeof wasmModules[number];
