// Generated by gen-adapters.ts (ADR-0004 Phase 0) — do not edit.
// Source: cad-schema.json boundaries [588b1e6aaa9e]
// Target: browser / sync-wasm-adapter

// Browser SyncWasmAdapter — wraps the sync WASM functions from pkg-sync.
// merge_docs IS included — SyncClient calls it after network.postSync() returns
// the merged server bytes. It is a local merge, not a network call.
//
// get_replay_ops is derived from get_ops + filter(enabled) because
// get_replay_ops is not re-exported from the browser WASM generated bindings.

import { create_doc, apply_op, merge_docs, get_ops, get_op_count, set_op_enabled, set_group_enabled, rollback_to, get_name, set_name, doc_hash } from './pkg-sync/plat_sync.js';
import type { SyncWasmAdapter } from '../../sync/ts/shared/wasm-adapter';
import type { CadOperation } from '../../sync/ts/shared/types';

/** Real browser SyncWasmAdapter — use in CadDocumentManagerBase constructor. */
export const browserSyncWasmAdapter: SyncWasmAdapter = {
    create_doc: () => Promise.resolve(create_doc()),
    apply_op: (doc: Uint8Array, opJson: string) => Promise.resolve(apply_op(doc, opJson)),
    merge_docs: (local: Uint8Array, remote: Uint8Array) => Promise.resolve(merge_docs(local, remote)),
    get_ops: (doc: Uint8Array) => Promise.resolve(get_ops(doc)),
    get_op_count: (doc: Uint8Array) => Promise.resolve(get_op_count(doc)),
    set_op_enabled: (doc: Uint8Array, opId: string, enabled: boolean) => Promise.resolve(set_op_enabled(doc, opId, enabled)),
    set_group_enabled: (doc: Uint8Array, groupId: string, enabled: boolean) => Promise.resolve(set_group_enabled(doc, groupId, enabled)),
    rollback_to: (doc: Uint8Array, actorId: string, toIndex: number) => Promise.resolve(rollback_to(doc, actorId, toIndex)),
    get_replay_ops: (doc) => {
        const all: CadOperation[] = JSON.parse(get_ops(doc));
        return Promise.resolve(JSON.stringify(all.filter(o => o.enabled)));
    },
    get_name: (doc: Uint8Array) => Promise.resolve(get_name(doc)),
    set_name: (doc: Uint8Array, name: string) => Promise.resolve(set_name(doc, name)),
    doc_hash: (doc: Uint8Array) => Promise.resolve(doc_hash(doc)),
};
