// Generated by gen-adapters.ts (ADR-0004 Phase 0) — do not edit.
// Source: cad-schema.json boundaries [588b1e6aaa9e]
// Target: sync-client (SyncWasmAdapter interface)

/**
 * SyncWasmAdapter — interface for the sync WASM module.
 *
 * Implemented by:
 *   - Real WASM: wrap the generated async functions from sync-wasm.generated.ts
 *   - Tests: wrap the same generated functions directly (no mock)
 *
 * All methods are async — matches wasm-bindgen generated signatures.
 * Generated from cad-schema.json boundaries (clientAdapter:true entries).
 * 12 methods.
 */
export interface SyncWasmAdapter {
  create_doc(): Promise<Uint8Array>;
  apply_op(doc: Uint8Array, opJson: string): Promise<Uint8Array>;
  merge_docs(local: Uint8Array, remote: Uint8Array): Promise<Uint8Array>;
  get_ops(doc: Uint8Array): Promise<string>;
  get_op_count(doc: Uint8Array): Promise<number>;
  set_op_enabled(doc: Uint8Array, opId: string, enabled: boolean): Promise<Uint8Array>;
  set_group_enabled(doc: Uint8Array, groupId: string, enabled: boolean): Promise<Uint8Array>;
  rollback_to(doc: Uint8Array, actorId: string, toIndex: number): Promise<Uint8Array>;
  get_replay_ops(doc: Uint8Array): Promise<string>;
  get_name(doc: Uint8Array): Promise<string>;
  set_name(doc: Uint8Array, name: string): Promise<Uint8Array>;
  doc_hash(doc: Uint8Array): Promise<string>;
}
