// Generated by gen-adapters.ts (ADR-0004 Phase 0) — do not edit.
// Source: cad-schema.json boundaries [588b1e6aaa9e]
// Target: cf-worker / plat-sync

/**
 * plat-sync WASM loader for Cloudflare Workers.
 *
 * Lazy-init pattern matching truck-wasm loader.
 * Generated from cad-schema.json boundaries — 14 exports.
 */

// Wrangler: default import is WebAssembly.Module.
// vitest (vite-plugin-wasm): default is undefined, namespace has instantiated exports.
import wasmDefault from '../pkg-sync/plat_sync_bg.wasm';
import * as wasmStar from '../pkg-sync/plat_sync_bg.wasm';
// @ts-expect-error — generated glue, no .d.ts for bg.js
import * as bg from '../pkg-sync/plat_sync_bg.js';

let initialized = false;

async function initSyncWasm(): Promise<void> {
  if (initialized) return;

  if (wasmDefault instanceof WebAssembly.Module) {
    // Wrangler: instantiate from Module with bg glue as imports
    const glueImports: WebAssembly.ModuleImports = {};
    for (const [key, value] of Object.entries(bg)) {
      if (typeof value === 'function') {
        glueImports[key] = value as WebAssembly.ImportValue;
      }
    }
    const instance = await WebAssembly.instantiate(wasmDefault, {
      './plat_sync_bg.js': glueImports,
    });
    bg.__wbg_set_wasm(instance.exports);
  } else {
    // vitest (vite-plugin-wasm): namespace has already-instantiated exports
    bg.__wbg_set_wasm(wasmStar as unknown as WebAssembly.Exports);
  }
  initialized = true;
}

/** Result of merge_docs_with_info — tells callers if the merge introduced new ops. */
export interface SyncMergeResult {
  doc: Uint8Array<ArrayBuffer>;
  localOpCount: number;
  mergedOpCount: number;
  hadNewOps: boolean;
}

export async function syncCreate(): Promise<Uint8Array<ArrayBuffer>> {
  await initSyncWasm();
  return bg.create_doc() as Uint8Array<ArrayBuffer>;
}

export async function syncApplyOp(doc: Uint8Array, opJson: string): Promise<Uint8Array<ArrayBuffer>> {
  await initSyncWasm();
  return bg.apply_op(doc, opJson) as Uint8Array<ArrayBuffer>;
}

export async function syncMergeDocs(local: Uint8Array, remote: Uint8Array): Promise<Uint8Array<ArrayBuffer>> {
  await initSyncWasm();
  return bg.merge_docs(local, remote) as Uint8Array<ArrayBuffer>;
}

export async function syncMergeDocsWithInfo(local: Uint8Array, remote: Uint8Array): Promise<SyncMergeResult> {
  await initSyncWasm();
  return bg.merge_docs_with_info(local, remote) as SyncMergeResult;
}

export async function syncGetOps(doc: Uint8Array): Promise<string> {
  await initSyncWasm();
  return bg.get_ops(doc) as string;
}

export async function syncGetOpCount(doc: Uint8Array): Promise<number> {
  await initSyncWasm();
  return bg.get_op_count(doc) as number;
}

export async function syncSetOpEnabled(doc: Uint8Array, opId: string, enabled: boolean): Promise<Uint8Array<ArrayBuffer>> {
  await initSyncWasm();
  return bg.set_op_enabled(doc, opId, enabled) as Uint8Array<ArrayBuffer>;
}

export async function syncSetGroupEnabled(doc: Uint8Array, groupId: string, enabled: boolean): Promise<Uint8Array<ArrayBuffer>> {
  await initSyncWasm();
  return bg.set_group_enabled(doc, groupId, enabled) as Uint8Array<ArrayBuffer>;
}

export async function syncRollbackTo(doc: Uint8Array, actorId: string, toIndex: number): Promise<Uint8Array<ArrayBuffer>> {
  await initSyncWasm();
  return bg.rollback_to(doc, actorId, toIndex) as Uint8Array<ArrayBuffer>;
}

export async function syncExportOpsSince(doc: Uint8Array, sinceIndex: number): Promise<string> {
  await initSyncWasm();
  return bg.export_ops_since(doc, sinceIndex) as string;
}

export async function syncValidateOp(opJson: string): Promise<boolean> {
  await initSyncWasm();
  return bg.validate_op(opJson) as boolean;
}

/** Returns enabled ops in index order — the geometry layer executes each in sequence. */
export async function syncGetReplayOps(doc: Uint8Array): Promise<string> {
  await initSyncWasm();
  return bg.get_replay_ops(doc) as string;
}

export async function syncGetName(doc: Uint8Array): Promise<string> {
  await initSyncWasm();
  return bg.get_name(doc) as string;
}

export async function syncSetName(doc: Uint8Array, name: string): Promise<Uint8Array<ArrayBuffer>> {
  await initSyncWasm();
  return bg.set_name(doc, name) as Uint8Array<ArrayBuffer>;
}

export async function syncDocHash(doc: Uint8Array): Promise<string> {
  await initSyncWasm();
  return bg.doc_hash(doc) as string;
}
