// Generated by gen-adapters.ts (ADR-0004 Phase 0) — do not edit.
// Source: cad-schema.json boundaries [6edb2ec515ab]
// Target: cf-worker / truck-geometry

/**
 * Headless truck-cad WASM loader for Cloudflare Workers.
 *
 * Lazy-init pattern: import the module, instantiate with glue imports on first use.
 * Generated from cad-schema.json boundaries — 42 commands.
 */

// Wrangler: default import is WebAssembly.Module.
// vitest (vite-plugin-wasm): default is undefined, namespace has instantiated exports.
import wasmDefault from '../pkg/truck_cad_bg.wasm';
import * as wasmStar from '../pkg/truck_cad_bg.wasm';
// @ts-expect-error — no .d.ts for the bg.js glue (generated code)
import * as bg from '../pkg/truck_cad_bg.js';

let initialized = false;

export async function initHeadlessWasm(): Promise<typeof bg> {
  if (initialized) return bg;

  if (wasmDefault instanceof WebAssembly.Module) {
    // Wrangler: instantiate from Module with bg glue as imports
    const glueImports: WebAssembly.ModuleImports = {};
    for (const [key, value] of Object.entries(bg)) {
      if (typeof value === 'function') {
        glueImports[key] = value as WebAssembly.ImportValue;
      }
    }
    const instance = await WebAssembly.instantiate(wasmDefault, {
      './truck_cad_bg.js': glueImports,
    });
    bg.__wbg_set_wasm(instance.exports);
    (instance.exports as unknown as { __wbindgen_start: () => void }).__wbindgen_start();
  } else {
    // vitest (vite-plugin-wasm): namespace has already-instantiated exports
    bg.__wbg_set_wasm(wasmStar as unknown as WebAssembly.Exports);
  }
  initialized = true;
  return bg;
}

// Re-export the HeadlessController type
export type { HeadlessController } from '../pkg/truck_cad.js';
